const {test}=require('node:test');const assert=require('node:assert/strict');
const {Simulation}=require('../.test-build/simulation/Simulation.js');
const {minionStats}=require('../.test-build/data/combat.js');
const {guardianRanks}=require('../.test-build/data/guardian.js');
const {nextLevelXp}=require('../.test-build/data/progression.js');
const {Progression,initialProgression}=require('../.test-build/simulation/Progression.js');
const {XPRewards,shareXP}=require('../.test-build/simulation/XPRewards.js');
const {chargeContact}=require('../.test-build/simulation/GuardianSkills.js');
const {applyStatus,slowFactor}=require('../.test-build/simulation/Statuses.js');
const ticks=(s,n)=>{for(let i=0;i<n;i++)s.advance(1000/30);};
function fixture(level=1){const s=new Simulation();s.state.spawnedWaves=2;s.state.units={guardian:s.hero};Object.assign(s.hero,{x:750,y:575});if(level>1)s.progression.award('fixture',Array.from({length:level-1},(_,i)=>nextLevelXp(i+1)).reduce((a,b)=>a+b,0));s.skills.refreshStats();s.drainEvents();return s;}
function minion(s,id='enemy',team='red',x=790,y=575){const u={id,kind:team==='red'?'minion-red':'minion-blue',team,x,y,...minionStats,hp:240,armor:0,speed:0,damage:0,readyTick:0,protectionTick:0};s.state.units[id]=u;return u;}
function learn(s,skill,rank=1){for(let i=0;i<rank;i++){s.send({type:'learn',skill,requestId:`learn-${skill}-${i}`});ticks(s,1);}s.drainEvents();}
const cast=(s,skill,extra={},id='cast')=>s.send({type:'cast',skill,requestId:id,...extra});
test('normal eligible minion deaths grant60 XP and allies may last hit',()=>{const s=fixture(),e=minion(s);s.hit(s.hero,e,1);s.hit({...s.hero,id:'ally',kind:'minion-blue'},e,240);assert.equal(s.state.heroProgression.xp,60);assert.equal(s.state.gold,265);const second=minion(s,'enemy2');s.hit(s.hero,second,240);assert.equal(s.state.heroProgression.level,2);assert.equal(s.state.heroProgression.xp,40);assert.equal(s.state.heroProgression.skillPoints,2);assert.equal(s.hero.maxHp,1260);assert.equal(s.hero.damage,83);assert.equal(s.drainEvents().filter(e=>e.type==='xp').length,2);});
test('recent positive damage includes dead heroes and keeps their deadline/HP0',()=>{const s=fixture(),e=minion(s);s.hit(s.hero,e,1);s.hero.hp=0;s.hero.respawnTick=151;s.hit({...s.hero,id:'ally',kind:'minion-blue'},e,240);assert.equal(s.state.heroProgression.xp,60);assert.equal(s.hero.hp,0);assert.equal(s.hero.respawnTick,151);});
test('participation expires after300 ticks while exact300 still qualifies',()=>{for(const delta of [300,301]){const s=fixture(),e=minion(s);s.hit(s.hero,e,1);s.hero.x=450;s.clock.tick=delta;s.hit({...s.hero,id:'ally',kind:'minion-blue'},e,240);assert.equal(s.state.heroProgression.xp,delta===300?60:0);}});
test('assistance radius includes240, excludes beyond and blocked LOS/dead proximity',()=>{for(const [distance,dead,expected] of [[240,false,60],[240.01,false,0],[100,true,0]]){const s=fixture(),e=minion(s,'enemy','red',750+distance);s.hero.hp=dead?0:1200;s.hit({...s.hero,id:'ally',kind:'minion-blue'},e,240);assert.equal(s.state.heroProgression.xp,expected);}const s=fixture(),e=minion(s,'enemy','red',1000,500);s.hit({...s.hero,id:'ally',kind:'minion-blue'},e,240);assert.equal(s.state.heroProgression.xp,0);});
test('enemy lives deduplicate deaths but reused IDs receive fresh XP/Gold',()=>{const s=fixture(),e=minion(s);s.hit(s.hero,e,240);s.hit(s.hero,e,240);assert.equal(s.state.heroProgression.xp,60);const next=minion(s);s.hit(s.hero,next,240);assert.equal(s.state.heroProgression.level,2);assert.equal(s.state.heroProgression.xp,40);assert.notEqual(e.lifeId,next.lifeId);assert.equal(s.state.gold,280);});
test('shared XP pools assign stable remainders and discard LV20 quota',()=>{assert.deepEqual(shareXP(61,['b','a','c','a']),[{id:'a',amount:21},{id:'b',amount:20},{id:'c',amount:20}]);const rewards=new XPRewards('test'),target={id:'enemy',kind:'minion-red',team:'red',x:750,y:575,hp:0};const a=initialProgression(),b=initialProgression();b.level=20;const heroes=[{unit:{id:'b',team:'blue',hp:1,x:750,y:575},progression:new Progression(b)},{unit:{id:'a',team:'blue',hp:1,x:750,y:575},progression:new Progression(a)}];rewards.award(target,1,heroes,{});assert.equal(a.xp,30);assert.equal(b.xp,0);assert.equal(rewards.award(target,1,heroes,{}).length,0);for(const bad of [NaN,-1,1.2,Infinity])assert.deepEqual(shareXP(bad,['a']),[]);});
test('friendly, wall, despawn and terminal state grant no XP',()=>{const s=fixture(),a=minion(s,'ally','blue');s.hit(s.hero,a,240);assert.equal(a.hp,240);assert.equal(s.state.heroProgression.xp,0);const e=minion(s);delete s.state.units[e.id];assert.equal(s.state.heroProgression.xp,0);s.state.match.result={outcome:'victory'};s.hit(s.hero,e,240);assert.equal(e.hp,240);});
for(let level=1;level<=20;level++)test(`derived LV${level} stats preserve HP fraction without accumulation`,()=>{const s=fixture();s.hero.hp=600;if(level>1)s.progression.award('levels',Array.from({length:level-1},(_,i)=>nextLevelXp(i+1)).reduce((a,b)=>a+b,0));s.skills.refreshStats();assert.equal(s.hero.maxHp,1200+60*(level-1));assert.equal(s.hero.damage,80+3*(level-1));assert.equal(s.hero.armor,20+level-1);assert.equal(s.hero.hp,s.hero.maxHp/2);for(let i=0;i<10;i++)s.skills.refreshStats();assert.equal(s.hero.hp,s.hero.maxHp/2);});
test('Fortitude uses gates18/20, two points and additive growth HP',()=>{const s=fixture(17);s.send({type:'learn',skill:'fortitude',requestId:'early'});ticks(s,1);assert.equal(s.state.heroProgression.fortitude,0);s.progression.award('18',nextLevelXp(17));s.skills.refreshStats();s.hero.hp=s.hero.maxHp/2;learn(s,'fortitude');assert.equal(s.state.heroProgression.fortitude,1);assert.equal(s.hero.maxHp,2220*1.05);s.progression.award('20',nextLevelXp(18)+nextLevelXp(19));s.skills.refreshStats();s.send({type:'learn',skill:'fortitude',requestId:'second'});ticks(s,1);assert.equal(s.hero.maxHp,2574);assert.equal(s.hero.armor,45);assert.equal(s.state.heroProgression.skillPoints,18);});
for(let rank=1;rank<=5;rank++){
 test(`Q rank${rank} exact damage, stun endpoint and accepted cooldown`,()=>{const s=fixture(2*rank-1),e=minion(s);e.hp=e.maxHp=1000;learn(s,'bash',rank);const start=s.clock.tick+1;cast(s,'bash');ticks(s,1);assert.equal(s.state.skills.ready.bash,start+[300,285,270,255,240][rank-1]);assert.equal(e.hp,1000);ticks(s,6);assert.equal(e.hp,1000-[80,95,110,125,140][rank-1]);const status=e.statuses.find(x=>x.type==='stun');assert.equal(status.expiresTick-s.clock.tick,[15,18,21,24,27][rank-1]);ticks(s,status.expiresTick-s.clock.tick);assert.equal(e.statuses.length,0);});
 test(`W rank${rank} taunt keeps enemy attacks/cooldowns`,()=>{const s=fixture(2*rank-1),e=minion(s);e.damage=18;learn(s,'taunt',rank);const start=s.clock.tick+1;cast(s,'taunt');ticks(s,7);assert.equal(s.state.skills.ready.taunt,start+[360,345,330,315,300][rank-1]);assert.equal(e.statuses.find(x=>x.type==='taunt').expiresTick-s.clock.tick,[30,33,36,39,42][rank-1]);ticks(s,12);assert.ok(s.hero.hp<s.hero.maxHp);assert.equal(e.targetId,'guardian');});
 test(`E rank${rank} hits first enemy once and applies movement slow`,()=>{const s=fixture(2*rank-1),e=minion(s,'enemy','red',850);e.hp=e.maxHp=1000;const other=minion(s,'other','red',870);learn(s,'charge',rank);const start=s.clock.tick+1;cast(s,'charge',{direction:{x:1,y:0}});ticks(s,12);assert.equal(e.hp,1000-[40,50,60,70,80][rank-1]);assert.equal(other.hp,240);assert.ok(Math.hypot(s.hero.x-e.x,s.hero.y-e.y)>=32-1e-7);assert.equal(s.state.skills.ready.charge,start+[420,405,390,375,360][rank-1]);assert.equal(slowFactor(e,s.clock.tick),1-[.2,.25,.3,.35,.4][rank-1]);assert.equal(s.drainEvents().filter(x=>x.type==='damage'&&x.castId).length,1);});
}
for(let rank=1;rank<=3;rank++)test(`R rank${rank} grants once, caps minion shield and remains stationary`,()=>{const s=fixture([6,11,16][rank-1]),a=minion(s,'ally','blue',710);const site={...a,id:'tower',kind:'tower',x:660,y:650,hp:650,maxHp:650};s.state.structures.tower=site;learn(s,'zone',rank);cast(s,'zone');ticks(s,10);assert.equal(s.hero.shield.remaining,[120,180,240][rank-1]);assert.equal(a.shield.remaining,72);assert.equal(a.armor,[10,15,20][rank-1]);assert.equal(site.shield,undefined);const z=structuredClone(s.state.skills.zones[0]);s.hero.x=450;a.x=450;ticks(s,1);assert.equal(s.state.skills.zones[0].x,z.x);assert.equal(a.armor,0);s.hit({...a,id:'red',team:'red'},a,30);assert.equal(a.shield.remaining,42);a.x=710;ticks(s,1);assert.equal(a.shield.remaining,42);ticks(s,z.expiresTick-s.clock.tick);assert.equal(a.shield,undefined);assert.equal(s.state.skills.zones.length,0);});
test('Q validation rejects invalid target/LOS/rank/cooldown and never retargets',()=>{const s=fixture(),e=minion(s);cast(s,'bash');ticks(s,1);assert.equal(s.state.skills.ready.bash,0);learn(s,'bash');cast(s,'bash',{targetId:'guardian'},'invalid');ticks(s,1);assert.equal(s.state.skills.ready.bash,0);cast(s,'bash',{},'valid');ticks(s,1);const ready=s.state.skills.ready.bash;e.x=1000;minion(s,'replacement');ticks(s,6);assert.equal(s.state.units.replacement.hp,240);cast(s,'bash',{},'cooldown');ticks(s,3);assert.equal(s.state.skills.ready.bash,ready);});
test('accepted casts interrupt unfinished basics and cannot reset readyTick',()=>{const s=fixture(),e=minion(s);e.hp=1000;learn(s,'bash');s.send({type:'attack'});ticks(s,1);const ready=s.hero.readyTick;cast(s,'bash');ticks(s,7);assert.equal(e.hp,920);assert.equal(s.hero.readyTick,ready);assert.equal(s.drainEvents().filter(x=>x.type==='damage').length,1);});
test('stun cancels cast/attack without losing spent cooldown',()=>{const s=fixture(),e=minion(s);learn(s,'bash');cast(s,'bash');ticks(s,1);const ready=s.state.skills.ready.bash;applyStatus(s.hero,{type:'stun',sourceId:e.id,sourceLife:'enemy',startTick:s.clock.tick,expiresTick:s.clock.tick+30,magnitude:1});ticks(s,7);assert.equal(e.hp,240);assert.equal(s.state.skills.cast,undefined);assert.equal(s.state.skills.ready.bash,ready);});
test('taunt invalidates after distance, source death or prolonged LOS loss',()=>{for(const mode of ['distance','death','los']){const s=fixture(),e=minion(s);learn(s,'taunt');cast(s,'taunt');ticks(s,7);assert.ok(e.statuses.length);if(mode==='distance')e.x=1050;if(mode==='death')s.hero.hp=0;if(mode==='los'){s.hero.x=850;s.hero.y=500;e.x=1060;e.y=500;}ticks(s,8);assert.equal(e.statuses.length,0);}});
test('Charge allies block harmlessly, terrain/bridge stop straight and cannot tunnel',()=>{const s=fixture(),ally=minion(s,'ally','blue',830);learn(s,'charge');cast(s,'charge',{direction:{x:1,y:0}});ticks(s,15);assert.ok(s.hero.x<=798+1e-7);assert.equal(ally.hp,240);const t=fixture();t.hero.x=850;t.hero.y=500;learn(t,'charge');cast(t,'charge',{direction:{x:1,y:0}});ticks(t,15);assert.ok(t.hero.x<=860+1e-7);assert.equal(t.hero.y,500);const contact=chargeContact(t.hero,1000,0,t.state);assert.ok(contact.fraction<.000001);});
test('charge direction validation and zero-blocked path spend nothing',()=>{const s=fixture();learn(s,'charge');cast(s,'charge',{direction:{x:0,y:0}});ticks(s,1);assert.equal(s.state.skills.ready.charge,0);s.hero.x=860;s.hero.y=500;cast(s,'charge',{direction:{x:1,y:0}},'blocked');ticks(s,1);assert.equal(s.state.skills.ready.charge,0);});
test('direct damage bypasses shield/armor, physical absorbs once and death cleans zones',()=>{const s=fixture(6),enemy=minion(s);learn(s,'zone');cast(s,'zone');ticks(s,10);const hp=s.hero.hp;s.hit(enemy,s.hero,20,'direct');assert.equal(s.hero.hp,hp-20);assert.equal(s.hero.shield.remaining,120);s.hit(enemy,s.hero,120*(1+s.hero.armor/100));assert.equal(s.hero.shield.remaining,0);assert.equal(s.hero.hp,hp-20);s.hit(enemy,s.hero,10000,'direct');assert.equal(s.state.skills.zones.length,0);assert.equal(s.hero.shield,undefined);});
test('near-base passive uses footprint edge, LOS and immediate exit/base death',()=>{const s=fixture();s.hero.x=642;s.hero.y=600;ticks(s,1);assert.equal(s.hero.armor,25);s.hero.x=642.01;ticks(s,1);assert.equal(s.hero.armor,20);s.hero.x=450;s.state.bases['blue-base'].hp=0;s.skills.refreshStats();assert.equal(s.hero.armor,20);});
test('statuses stack strongest/later duration without multiplication or attack reset',()=>{const s=fixture(),e=minion(s);e.readyTick=100;const base={type:'slow',sourceId:'guardian',sourceLife:'g',startTick:0,expiresTick:30,magnitude:.2};applyStatus(e,base);applyStatus(e,{...base,magnitude:.4,expiresTick:20});assert.equal(slowFactor(e,1),.6);assert.equal(e.statuses.length,1);assert.equal(e.statuses[0].expiresTick,30);applyStatus(e,{...base,type:'stun',expiresTick:15});assert.equal(e.readyTick,100);});
test('pause/timeScale freeze casts, status expiry and respawn; fresh restart resets skills',()=>{const s=fixture(6),e=minion(s);learn(s,'bash');cast(s,'bash');ticks(s,1);s.setPaused(true);const tick=s.clock.tick,ready=s.state.skills.ready.bash;ticks(s,30);assert.equal(s.clock.tick,tick);assert.equal(s.state.skills.ready.bash,ready);s.setPaused(false);s.setTimeScale(.25);ticks(s,24);assert.equal(s.clock.tick,tick+6);assert.equal(e.hp,160);const n=new Simulation();assert.equal(n.state.skills.cast,undefined);assert.equal(n.state.skills.zones.length,0);assert.equal(n.state.skills.ready.bash,0);});
test('cast state/events remain deterministic across partitions',()=>{const a=fixture(6),b=fixture(6);for(const s of [a,b]){minion(s);learn(s,'bash');cast(s,'bash');}for(let i=0;i<60;i++)a.advance(1000/30);for(let i=0;i<120;i++)b.advance(1000/60);assert.deepEqual(a.state,b.state);assert.deepEqual(a.drainEvents(),b.drainEvents());});

test('complete skill and Fortitude allocation spends exactly20 points',()=>{const s=fixture(20);for(const skill of ['bash','taunt','charge'])learn(s,skill,5);learn(s,'zone',3);learn(s,'fortitude',2);assert.equal(s.state.heroProgression.skillPoints,0);assert.equal(s.state.heroProgression.fortitude,2);assert.deepEqual(s.state.heroProgression.ranks,{bash:5,taunt:5,charge:5,zone:3});});
test('duplicate cast requests and shared lock produce one effect without extra cooldown spend',()=>{const s=fixture(3);minion(s);learn(s,'bash');learn(s,'taunt');cast(s,'bash',{},'a');cast(s,'taunt',{},'b');cast(s,'bash',{},'a');ticks(s,7);assert.equal(s.state.skills.ready.taunt,0);assert.equal(s.drainEvents().filter(e=>e.type==='cast-accepted').length,1);});
test('Charge travel clamps at every rank max and cancels safely on newly built obstacle',()=>{for(let rank=1;rank<=5;rank++){const s=fixture(2*rank-1);s.hero.x=1200;s.hero.y=600;learn(s,'charge',rank);cast(s,'charge',{direction:{x:1,y:0}});ticks(s,20);assert.equal(s.hero.x,1200+[144,168,192,216,240][rank-1]);}const s=fixture();learn(s,'charge');cast(s,'charge',{direction:{x:1,y:0}});ticks(s,1);s.state.structures.wall={id:'wall',kind:'wall',team:'blue',x:810,y:575,hp:400,armor:0,radius:24,columns:1,rows:1};ticks(s,15);assert.ok(s.hero.x<=766+1e-7);assert.ok(s.state.skills.ready.charge>0);assert.equal(s.state.structures.wall.hp,400);});
test('slow reduces movement without changing attack timing and stun prevents movement',()=>{const s=fixture(),e=minion(s);e.x=1100;e.speed=95;e.damage=18;applyStatus(e,{type:'slow',sourceId:'guardian',sourceLife:'g',startTick:0,expiresTick:30,magnitude:.4});const start=e.x;ticks(s,1);assert.ok(Math.hypot(e.x-start,e.y-575)<=95/30*.6+1e-7);applyStatus(e,{type:'stun',sourceId:'guardian',sourceLife:'g',startTick:1,expiresTick:20,magnitude:1});const x=e.x,y=e.y;ticks(s,10);assert.equal(e.x,x);assert.equal(e.y,y);assert.equal(e.cooldownTicks,30);});
test('R all cooldown/duration endpoints and late entrants never get shields',()=>{for(let rank=1;rank<=3;rank++){const s=fixture([6,11,16][rank-1]);learn(s,'zone',rank);const start=s.clock.tick+1;cast(s,'zone');ticks(s,10);assert.equal(s.state.skills.ready.zone,start+[1650,1500,1350][rank-1]);assert.equal(s.state.skills.zones[0].expiresTick-s.clock.tick,[120,135,150][rank-1]);const a=minion(s,'late','blue',710);ticks(s,1);assert.equal(a.shield,undefined);assert.equal(a.armor,[10,15,20][rank-1]);}});
test('taunt expires into normal nearest-target AI without resetting cooldown',()=>{const s=fixture(),e=minion(s),a=minion(s,'ally','blue',820);e.damage=18;learn(s,'taunt');cast(s,'taunt');ticks(s,7);const expiry=e.statuses.find(x=>x.type==='taunt').expiresTick;ticks(s,1);assert.equal(e.targetId,'guardian');const ready=e.readyTick;ticks(s,expiry-s.clock.tick);assert.equal(e.targetId,a.id);assert.ok(e.readyTick>=ready);});
test('death/terminal clean casts/zones and preserve cooldowns through respawn',()=>{const s=fixture(6),e=minion(s);learn(s,'zone');cast(s,'zone');ticks(s,10);const ready=s.state.skills.ready.zone;s.hit(e,s.hero,99999,'direct');assert.equal(s.state.skills.zones.length,0);const deadline=s.hero.respawnTick;ticks(s,deadline-s.clock.tick);assert.equal(s.hero.hp,1500);assert.equal(s.state.skills.ready.zone,ready);s.state.bases['red-base'].hp=0;ticks(s,1);assert.equal(cast(s,'zone',{},'after-end'),false);assert.equal(s.state.skills.cast,undefined);});

test('shared9-tick recovery prevents a fresh basic attack before recovery ends',()=>{const s=fixture(),e=minion(s);e.hp=e.maxHp=1000;learn(s,'bash');s.state.attacking=true;const accepted=s.clock.tick+1;cast(s,'bash');ticks(s,7);assert.equal(e.hp,920);assert.equal(s.hero.strike,undefined);assert.equal(s.hero.readyTick,0);ticks(s,2);assert.equal(s.hero.strike,undefined);ticks(s,1);assert.equal(s.hero.strike.atTick,accepted+9+6);assert.equal(s.hero.readyTick,accepted+9+23);});

test('Taunt completion redirects targeting before same-tick combat can restart an allied windup',()=>{const s=fixture(),e=minion(s,'enemy','red',820),a=minion(s,'ally','blue',815);e.speed=a.speed=0;learn(s,'taunt');cast(s,'taunt');ticks(s,6);e.targetId=a.id;e.strike=undefined;e.readyTick=0;ticks(s,1);assert.equal(e.targetId,'guardian');assert.notEqual(e.strike?.targetId,a.id);});
test('an older taunt cannot steal the winning source or cancel its valid attack',()=>{const s=fixture(),e=minion(s);const status={type:'taunt',sourceId:'guardian',sourceLife:'new',startTick:10,expiresTick:40,magnitude:1};applyStatus(e,status);e.strike={targetId:'guardian',atTick:30};applyStatus(e,{...status,sourceId:'old-hero',startTick:9,expiresTick:45});assert.equal(e.targetId,'guardian');assert.equal(e.strike.targetId,'guardian');assert.equal(e.statuses[0].expiresTick,45);});
