const {test}=require('node:test'),assert=require('node:assert/strict');
const {Simulation}=require('../.test-build/simulation/Simulation.js');
const {canAttack}=require('../.test-build/simulation/Combat.js');
const {blocked}=require('../.test-build/simulation/Collision.js');
const {combatStructures}=require('../.test-build/simulation/GameState.js');
const {minionStats}=require('../.test-build/data/combat.js');
const ticks=(s,n)=>{for(let i=0;i<n;i++)s.advance(1000/30);};
function fixture(){const s=new Simulation();s.state.units={guardian:s.hero};s.state.spawnedWaves=2;return s;}
function attacker(s,id,team,x,y){const u={id,team,kind:'minion-'+team,x,y,...minionStats,hp:240,speed:0,readyTick:0,protectionTick:0,windupTicks:0};s.state.units[id]=u;return u;}
function finish(s,team){const b=s.state.bases[team==='red'?'red-base':'blue-base'];b.hp=1;attacker(s,'finisher',team==='red'?'blue':'red',b.x+(team==='red'?-120:120),b.y);if(team==='blue')s.teleportHero(820,590);ticks(s,1);return s.drainEvents();}

test('approved bases initialize with authoritative HP/3x3 footprint and unchanged resources',()=>{const s=new Simulation();assert.equal(s.state.match.phase,'playing');for(const b of Object.values(s.state.bases)){assert.equal(b.hp,3000);assert.equal(b.maxHp,3000);assert.equal(b.columns,3);assert.equal(blocked(b.x,b.y,12,combatStructures(s.state)),true);}assert.equal(s.state.gold,250);assert.equal(s.state.wood,180);assert.equal(s.state.iron,30);assert.equal(Object.keys(s.state.structures).length,0);});
test('base melee reach measures world footprint edge and respects factions/LOS',()=>{const s=fixture(),b=s.state.bases['red-base'],a=attacker(s,'ally','blue',1490,600);assert.ok(canAttack(a,b,combatStructures(s.state)));a.x=1489;assert.equal(canAttack(a,b,combatStructures(s.state)),false);a.x=1490;assert.equal(canAttack({...a,team:'red'},b,combatStructures(s.state)),false);s.state.structures.blocker={...s.state.bases['blue-base'],id:'blocker',kind:'wall',x:1514,y:600,columns:1,rows:1};assert.equal(canAttack(a,b,combatStructures(s.state)),false);});
test('allied minion and Guardian damage enemy base through shared events/armor pipeline',()=>{const s=fixture();s.teleportHero(1480,600);s.send({type:'target',id:'red-base'});s.send({type:'attack'});ticks(s,7);assert.equal(s.state.bases['red-base'].hp,2920);assert.ok(s.drainEvents().some(e=>e.type==='damage'&&e.id==='red-base'&&e.sourceId==='guardian'&&e.amount===80));const a=attacker(s,'ally','blue',1490,600);ticks(s,1);assert.equal(s.state.bases['red-base'].hp,2902);assert.equal(a.targetId,'red-base');});
test('Tower targets opposing base independently and never attacks allied objective',()=>{const s=fixture(),b=s.state.bases['red-base'];s.state.structures.tower={...b,id:'tower',kind:'tower',team:'blue',x:1440,y:600,columns:1,rows:1,range:240,damage:18,cooldownTicks:24};ticks(s,1);assert.equal(b.hp,2982);assert.equal(s.state.bases['blue-base'].hp,3000);assert.equal(s.state.structures.tower.targetId,'red-base');});
for(const team of ['red','blue'])test(`${team} base destruction emits exactly one ${team==='red'?'victory':'defeat'} and no reward`,()=>{const s=fixture(),events=finish(s,team),outcome=team==='red'?'victory':'defeat';assert.equal(s.state.match.phase,outcome);assert.equal(s.state.bases[team+'-base'].hp,0);assert.equal(events.filter(e=>e.type==='death'&&e.id===team+'-base').length,1);assert.equal(events.filter(e=>e.type==='match-end'&&e.outcome===outcome).length,1);assert.equal(events.filter(e=>e.type==='reward').length,0);assert.equal(s.state.gold,250);ticks(s,500);assert.deepEqual(s.drainEvents(),[]);});
test('simultaneous lethal attacks choose defeat regardless of attacker insertion order',()=>{for(const order of [['blue','red'],['red','blue']]){const s=fixture();s.state.bases['blue-base'].hp=s.state.bases['red-base'].hp=1;for(const team of order){const u=attacker(s,team,team,team==='blue'?1490:450,600);u.targetId=team==='blue'?'red-base':'blue-base';u.targetSinceTick=1;u.decisionTick=100;}ticks(s,1);assert.equal(s.state.match.phase,'defeat');assert.equal(s.state.bases['blue-base'].hp,0);assert.equal(s.state.bases['red-base'].hp,0);assert.equal(s.drainEvents().filter(e=>e.type==='match-end').length,1);}});
test('terminal state rejects late commands, pause/resume/timeScale and freezes catch-up clock/AI/economy',()=>{const s=fixture();s.state.bases['red-base'].hp=1;attacker(s,'finisher','blue',1490,600);s.advance(100);assert.equal(s.clock.tick,1);s.drainEvents();const state=structuredClone(s.state),stats={...s.navigation.stats};for(const c of [{type:'attack'},{type:'move',x:1,y:0},{type:'place',kind:'wall',col:12,row:12,requestId:'late'}])assert.equal(s.send(c),false);s.setPaused(false);s.setTimeScale(2);assert.equal(s.teleportHero(500,600),false);ticks(s,600);assert.deepEqual(s.state,state);assert.deepEqual(s.navigation.stats,stats);assert.deepEqual(s.drainEvents(),[]);assert.equal(s.clock.tick,1);});
test('Guardian death/5s respawn is independent of outcome and selects a clear spawn',()=>{const s=fixture();s.hero.hp=0;s.hero.respawnTick=150;attacker(s,'occupied','blue',450,600);ticks(s,149);assert.equal(s.hero.hp,0);assert.equal(s.state.match.phase,'playing');ticks(s,1);assert.equal(s.hero.hp,1200);assert.equal(s.hero.protectionTick,210);assert.ok(Math.hypot(s.hero.x-450,s.hero.y-600)>=32);assert.equal(blocked(s.hero.x,s.hero.y,s.hero.radius,combatStructures(s.state)),false);});
test('terminal defeat cancels an otherwise pending Guardian respawn',()=>{const s=fixture();s.hero.hp=0;s.hero.respawnTick=150;finish(s,'blue');ticks(s,500);assert.equal(s.hero.hp,0);assert.equal(s.clock.tick,1);});
test('finite waves use the inherited ticks and enforce both faction caps',()=>{const s=new Simulation();ticks(s,1);assert.equal(s.state.spawnedWaves,1);ticks(s,239);assert.equal(s.state.spawnedWaves,2);ticks(s,600);assert.equal(s.state.spawnedWaves,2);const c=new Simulation();for(let i=0;i<40;i++)attacker(c,'cap-'+i,'red',1200+i,600);ticks(c,1);assert.equal(Object.values(c.state.units).filter(u=>u.team==='red').length,40);});
test('fresh restart resets objective state, resources, wave clock, caches, inputs and cooldowns repeatedly',()=>{let old=fixture();finish(old,'red');for(let i=0;i<5;i++){old.beginRestart();assert.equal(old.state.match.phase,'restarting');const s=new Simulation();assert.equal(s.clock.tick,0);assert.equal(s.clock.paused,false);assert.equal(s.state.match.phase,'playing');assert.equal(s.state.match.result,undefined);assert.equal(s.state.bases['blue-base'].hp,3000);assert.equal(s.state.bases['red-base'].hp,3000);assert.equal(s.hero.hp,1200);assert.equal(s.state.gold,250);assert.equal(s.state.wood,180);assert.equal(s.state.iron,30);assert.equal(s.state.spawnedWaves,0);assert.equal(s.hero.readyTick,0);assert.deepEqual(s.state.move,{x:0,y:0});assert.equal(s.state.attacking,false);assert.equal(s.navigation.stats.plans,0);assert.equal(s.navigation.routeFor('blue-0'),undefined);old=s;}});
test('match phase tracks pause/zero scale and all deadlines use simulation time',()=>{const s=new Simulation();s.setPaused(true);assert.equal(s.state.match.phase,'paused');ticks(s,100);assert.equal(s.clock.tick,0);s.setPaused(false);assert.equal(s.state.match.phase,'playing');s.setTimeScale(.25);ticks(s,120);assert.equal(s.clock.tick,30);s.setTimeScale(0);assert.equal(s.state.match.phase,'paused');ticks(s,50);assert.equal(s.clock.tick,30);s.setTimeScale(1);assert.equal(s.state.match.phase,'playing');});
test('normal unmodified waves reach defeat and drain-once events remain bounded',()=>{const s=new Simulation();let ends=0,deaths=0,maxUnits=0;for(let i=0;i<6000&&!s.ended;i++){ticks(s,1);maxUnits=Math.max(maxUnits,Object.keys(s.state.units).length);for(const e of s.drainEvents()){if(e.type==='match-end')ends++;if(e.type==='death'&&e.id==='blue-base')deaths++;}}assert.equal(s.state.match.phase,'defeat');assert.equal(ends,1);assert.equal(deaths,1);assert.ok(maxUnits<=13);assert.equal(s.navigation.stats.maxPlansPerTick,2);assert.ok(s.navigation.stats.maxExpandedPerPlan<=960);});
test('normal Guardian movement/attack reaches victory with unchanged stats and waves',()=>{const s=new Simulation();s.send({type:'attack'});s.send({type:'move',x:1,y:0});for(let i=0;i<3000&&!s.ended;i++){if(s.hero.x>=1480)s.send({type:'move',x:0,y:0});ticks(s,1);s.drainEvents();}assert.equal(s.state.match.phase,'victory');assert.equal(s.state.bases['red-base'].hp,0);assert.equal(s.state.bases['blue-base'].hp,3000);});
test('base objective determinism matches identical runs at 30/60 frame partitions through terminal result',()=>{const a=new Simulation(),b=new Simulation();for(const s of [a,b]){s.send({type:'attack'});s.send({type:'move',x:1,y:0});}for(let i=0;i<2400;i++)a.advance(1000/30);for(let i=0;i<4800;i++)b.advance(1000/60);assert.deepEqual(a.state,b.state);assert.deepEqual(a.drainEvents(),b.drainEvents());assert.deepEqual(a.navigation.stats,b.navigation.stats);assert.equal(a.state.match.phase,'victory');});
