const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Simulation}=require('../.test-build/simulation/Simulation.js');
const {Navigation,clearSegment}=require('../.test-build/simulation/Navigation.js');
const {blocked}=require('../.test-build/simulation/Collision.js');
const {minionStats}=require('../.test-build/data/combat.js');
const {buildings}=require('../.test-build/data/buildings.js');
const ticks=(s,n)=>{for(let i=0;i<n;i++)s.advance(1000/30);};
function minion(id,team,x,y){return {id,kind:'minion-'+team,team,x,y,...minionStats,hp:240,readyTick:0,protectionTick:0};}
function fixture(x=820,y=600){const s=new Simulation();s.state.units={guardian:s.hero,raider:minion('raider','red',x,y)};s.state.spawnedWaves=2;s.teleportHero(450,600);return s;}
function wall(s,col,row,team='blue',hp=400){const id=`fixture-${col}-${row}`;s.state.structures[id]={id,kind:'wall',team,x:(col+.5)*48,y:(row+.5)*48,col,row,...buildings.wall,hp,maxHp:hp,armor:0,radius:24,speed:0,windupTicks:0,readyTick:0,protectionTick:0,startTick:-60,completeTick:0,progress:1,constructionDamage:0};return s.state.structures[id];}

test('approved allies advance and exchange authoritative damage without player input',()=>{const s=new Simulation();const start=s.state.units['blue-2'].x;ticks(s,60);assert.ok(s.state.units['blue-2'].x>start);ticks(s,120);const events=s.drainEvents();assert.ok(events.some(e=>e.type==='damage'&&e.sourceId.startsWith('blue-')&&e.id.startsWith('red-')));assert.ok(events.some(e=>e.type==='damage'&&e.sourceId.startsWith('red-')&&e.id.startsWith('blue-')));assert.equal(s.state.attacking,false);assert.equal(s.state.wood,192);});
test('allied reinforcements use the shared clock, valid spawn points and faction cap',()=>{const s=new Simulation();ticks(s,239);assert.equal(s.state.units['blue-1-0'],undefined);ticks(s,1);for(let i=0;i<3;i++){const u=s.state.units[`blue-1-${i}`];assert.ok(u);assert.equal(u.team,'blue');assert.equal(blocked(u.x,u.y,u.radius,s.state.structures),false);}const c=new Simulation();for(const id of Object.keys(c.state.units))if(id.startsWith('blue-'))delete c.state.units[id];for(let i=0;i<40;i++)c.state.units[`cap-${i}`]=minion(`cap-${i}`,'blue',500,552);ticks(c,240);assert.ok(Object.values(c.state.units).filter(u=>u.kind==='minion-blue').length<=40);});
test('friendly units never attack each other; hostile ally death grants no player reward',()=>{const s=fixture();s.hero.hp=0;s.state.units.ally=minion('ally','blue',780,600);s.state.units.friend=minion('friend','blue',740,600);s.state.units.ally.hp=1;ticks(s,30);const events=s.drainEvents();assert.equal(s.state.units.ally,undefined);assert.equal(events.filter(e=>e.type==='death'&&e.id==='ally').length,1);assert.equal(events.filter(e=>e.type==='reward'&&e.id==='ally').length,0);assert.equal(s.state.gold,250);assert.ok(!events.some(e=>e.type==='damage'&&e.sourceId==='friend'&&e.id==='ally'));});
test('allied kill rewards a red minion exactly once and clears attack references',()=>{const s=fixture(820,600);s.hero.hp=0;s.state.units.ally=minion('ally','blue',780,600);s.state.units.raider.hp=1;s.state.units.raider.damage=0;ticks(s,50);const events=s.drainEvents();assert.equal(s.state.units.raider,undefined);assert.equal(s.state.gold,265);assert.equal(events.filter(e=>e.type==='reward'&&e.id==='raider').length,1);assert.notEqual(s.state.units.ally.targetId,'raider');assert.notEqual(s.state.units.ally.strike?.targetId,'raider');});
test('grid route crosses only the radius-safe bridge and uses four neighbors',()=>{const s=fixture(1250,430),u=s.state.units.raider,n=s.navigation;n.begin(s.state);const r=n.route(u,s.hero,s.state,1);assert.ok(r.points.length>0);r.points.forEach((p,i)=>{assert.equal(blocked(p.x,p.y,u.radius),false);assert.ok(clearSegment(i?r.points[i-1]:u,p,u.radius));if(i)assert.ok(p.x===r.points[i-1].x||p.y===r.points[i-1].y);if(p.x>880&&p.x<1040)assert.ok(p.y>=547&&p.y<=603);});});
test('real construction invalidates intersecting route and minion walks around an intact wall',()=>{const s=fixture();ticks(s,1);const before=s.navigation.routeFor('raider');assert.ok(before.points.some(p=>p.x===600&&p.y===600));s.send({type:'place',requestId:'reroute',kind:'wall',col:12,row:12});ticks(s,1);const r=s.navigation.routeFor('raider'),b=s.state.structures['built-reroute'];assert.ok(b);assert.ok(r.version>before.version);assert.ok(!r.points.some(p=>p.x===600&&p.y===600));let offset=false;for(let i=0;i<150;i++){ticks(s,1);const u=s.state.units.raider;offset ||= Math.abs(u.y-600)>25;assert.equal(blocked(u.x,u.y,u.radius,s.state.structures),false);}assert.ok(offset);assert.ok(s.state.units.raider.x<560);assert.equal(b.hp,400);});
test('structure removal increments topology and opens a shorter valid route',()=>{const s=fixture(),b=wall(s,12,12);ticks(s,1);const version=s.navigation.version;delete s.state.structures[b.id];ticks(s,30);assert.ok(s.navigation.version>version);const r=s.navigation.routeFor('raider');assert.ok(r.points.some(p=>p.x===600&&p.y===600));assert.equal(r.breachId,undefined);});
test('sealed bridge selects hostile wall, destroys it once, and resumes across freed collision',()=>{const s=fixture(1200,600);s.hero.hp=0;const a=wall(s,20,11,'blue',36),b=wall(s,20,12,'blue',36);ticks(s,1);assert.ok([a.id,b.id].includes(s.navigation.routeFor('raider').breachId));let crossed=false;for(let i=0;i<240;i++){ticks(s,1);const u=s.state.units.raider;assert.equal(blocked(u.x,u.y,u.radius,s.state.structures),false);crossed ||= u.x<950;}assert.ok(crossed);const e=s.drainEvents();assert.ok(e.some(e=>e.type==='damage'&&[a.id,b.id].includes(e.id)));assert.equal(e.filter(e=>e.type==='death'&&[a.id,b.id].includes(e.id)).length,1);assert.equal(s.state.gold,250);});
test('sealed friendly wall and permanent water cannot become breach targets',()=>{const s=fixture(1200,600);s.hero.hp=0;wall(s,20,11,'red');wall(s,20,12,'red');const before=structuredClone(s.state.structures);ticks(s,150);assert.deepEqual(s.state.structures,before);assert.ok(s.state.units.raider.x>1000);assert.equal(s.state.units.raider.breachId,undefined);assert.ok(!s.drainEvents().some(e=>e.type==='attack'));});
test('low-HP hostile breach beats a long detour but high HP retains the safe route',()=>{const s=fixture();s.hero.hp=0;const u=s.state.units.raider;const b=wall(s,12,12,'blue',1);wall(s,12,11);wall(s,12,13);s.navigation.begin(s.state);const fast=s.navigation.route(u,undefined,s.state,1);assert.equal(fast.breachId,b.id);b.hp=b.maxHp=400;const n=new Navigation();n.begin(s.state);assert.equal(n.route(u,undefined,s.state,1).breachId,undefined);});
test('planning budget, retry caching and priority remain bounded under a crowd',()=>{const s=fixture();s.hero.hp=0;for(let i=0;i<30;i++)s.state.units[`crowd-${i}`]=minion(`crowd-${i}`,'red',1200+i*3,600);ticks(s,40);assert.ok(s.navigation.stats.maxPlansPerTick<=2);assert.ok(s.navigation.stats.maxExpandedPerPlan<=960);for(const u of Object.values(s.state.units).filter(u=>u.kind.startsWith('minion')))assert.ok(s.navigation.routeFor(u.id));assert.ok(s.navigation.stats.plans<80);});
test('separation releases an overlapping pair without entering obstacles',()=>{const s=fixture();s.hero.hp=0;s.state.units.raider.x=1200;s.state.units.other=minion('other','red',1200,600);ticks(s,40);const a=s.state.units.raider,b=s.state.units.other;assert.ok(Math.hypot(a.x-b.x,a.y-b.y)>20);assert.equal(blocked(a.x,a.y,a.radius),false);assert.equal(blocked(b.x,b.y,b.radius),false);});
test('AI/combat/navigation stay deterministic across 30/60 FPS including construction and death',()=>{const a=new Simulation(),b=new Simulation();for(const s of [a,b])s.send({type:'place',requestId:'deterministic',kind:'wall',col:12,row:12});for(let i=0;i<900;i++)a.advance(1000/30);for(let i=0;i<1800;i++)b.advance(1000/60);assert.deepEqual(a.state,b.state);assert.deepEqual(a.drainEvents(),b.drainEvents());assert.deepEqual(a.navigation.stats,b.navigation.stats);});
test('pause freezes AI, routes, damage and economy; slow motion is absolute',()=>{const s=fixture();ticks(s,3);s.setPaused(true);const before=structuredClone(s.state),stats={...s.navigation.stats};ticks(s,90);assert.deepEqual(s.state,before);assert.deepEqual(s.navigation.stats,stats);s.setPaused(false);s.setTimeScale(.25);ticks(s,120);assert.equal(s.clock.tick,33);assert.ok(s.state.units.raider.x<before.units.raider.x);});
test('new simulation resets cached routes, planner counters, resources and allied HP',()=>{const s=new Simulation();ticks(s,300);const fresh=new Simulation();assert.equal(fresh.navigation.routeFor('blue-0'),undefined);assert.equal(fresh.navigation.stats.plans,0);assert.equal(fresh.state.gold,250);assert.equal(fresh.state.units['blue-0'].hp,240);});
test('separated lane recenters before a narrow bridge and all original solo waves remain reachable',()=>{const s=new Simulation();for(const id of Object.keys(s.state.units))if(id.startsWith('blue-'))delete s.state.units[id];s.send({type:'attack'});for(let i=0;i<900;i++){ticks(s,1);for(const id of Object.keys(s.state.units))if(id.startsWith('blue-'))delete s.state.units[id];for(const u of Object.values(s.state.units))assert.equal(blocked(u.x,u.y,u.radius,s.state.structures),false);}assert.equal(s.state.kills,6);assert.equal(s.state.gold,340);assert.equal(Object.values(s.state.units).filter(u=>u.team==='red').length,0);});
test('allied AI acquires and attacks an eligible hostile Tower through shared structure combat',()=>{const s=fixture();s.hero.hp=0;delete s.state.units.raider;s.state.units.ally=minion('ally','blue',740,600);const b=wall(s,14,12,'red',100);b.kind='tower';ticks(s,20);assert.equal(b.hp,82);assert.ok(s.drainEvents().some(e=>e.type==='damage'&&e.id===b.id&&e.sourceId==='ally'&&e.amount===18));});
test('opening another channel cancels an obsolete breach plan after target retention',()=>{const s=fixture(1200,600);s.hero.hp=0;const a=wall(s,20,11),b=wall(s,20,12);ticks(s,1);const selected=s.state.units.raider.breachId;assert.ok(selected);delete s.state.structures[selected===a.id?b.id:a.id];ticks(s,60);assert.equal(s.state.units.raider.breachId,undefined);assert.ok(s.state.structures[selected]);ticks(s,90);assert.ok(s.state.units.raider.x<950);});
