const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Simulation}=require('../.test-build/simulation/Simulation.js');
const {Progression,initialProgression}=require('../.test-build/simulation/Progression.js');
const {nextLevelXp,respawnTicks,enemyXp}=require('../.test-build/data/progression.js');
const ticks=(s,n)=>{for(let i=0;i<n;i++)s.advance(1000/30);};
const toLevel=level=>Array.from({length:level-1},(_,i)=>nextLevelXp(i+1)).reduce((a,b)=>a+b,0);
const learn=(s,skill,id=skill)=>s.send({type:'learn',skill,requestId:id});
const policy=(fn)=>{const old=enemyXp['minion-red'];enemyXp['minion-red']=80;try{fn();}finally{enemyXp['minion-red']=old;}}; // Explicit test-only XP amount, never production balance.
function duel(){const s=new Simulation();ticks(s,1);const e=s.state.units['red-0-0'];s.state.units={guardian:s.hero,[e.id]:e};s.state.spawnedWaves=2;Object.assign(e,{x:870,y:590,speed:0,damage:0});s.drainEvents();return {s,e};}

test('new matches have LV1, zero XP, one point and independent unlearned ranks',()=>{const a=new Simulation(),b=new Simulation();assert.deepEqual(a.state.heroProgression,initialProgression());a.state.heroProgression.ranks.bash=1;assert.equal(b.state.heroProgression.ranks.bash,0);});
test('all next-level thresholds use the specified formula and LV20 has no next level',()=>{for(let i=1;i<20;i++)assert.equal(nextLevelXp(i),80+25*(i-1));assert.equal(nextLevelXp(20),0);assert.equal(toLevel(20),5795);});
test('subthreshold XP persists, then exact threshold awards one level/point',()=>{const h=initialProgression(),p=new Progression(h);p.award('first',79);assert.equal(h.level,1);assert.equal(h.xp,79);assert.deepEqual(p.award('last',1).map(e=>e.type),['xp','level-up']);assert.deepEqual([h.level,h.xp,h.skillPoints],[2,0,2]);});
test('one award crosses multiple thresholds and retains the correct remainder',()=>{const h=initialProgression(),p=new Progression(h);const events=p.award('multi',192);assert.deepEqual([h.level,h.xp,h.skillPoints],[3,7,3]);assert.equal(events.filter(e=>e.type==='level-up').length,2);});
test('LV20 enforces the cap, exactly twenty total points and no further XP accumulation',()=>{const h=initialProgression(),p=new Progression(h);p.award('huge',99999);assert.deepEqual([h.level,h.xp,h.skillPoints],[20,0,20]);assert.deepEqual(p.award('after-cap',80),[]);assert.equal(h.level,20);});
test('duplicate XP source cannot award XP, level-ups or points twice',()=>{const h=initialProgression(),p=new Progression(h);p.award('unit-a',80);const before=structuredClone(h);assert.deepEqual(p.award('unit-a',5000),[]);assert.deepEqual(h,before);});
test('invalid XP values do not consume a reward source or mutate state',()=>{const h=initialProgression(),p=new Progression(h);for(const n of [0,-1,NaN,Infinity,1.5])assert.deepEqual(p.award('valid-later',n),[]);assert.deepEqual(h,initialProgression());p.award('valid-later',80);assert.equal(h.level,2);});
test('regular rank gates use LV1/3/5/7/9 and maximum rank five',()=>{const h=initialProgression(),p=new Progression(h);assert.equal(p.allocate('q1','bash').type,'skill-upgraded');assert.equal(p.allocate('q2-early','bash').reason,'Requires LV 3');p.award('training',toLevel(9));for(let rank=2;rank<=5;rank++)assert.equal(p.allocate(`q${rank}`,'bash').rank,rank);const before=h.skillPoints;assert.equal(p.allocate('q6','bash').reason,'Maximum skill rank');assert.equal(h.skillPoints,before);});
test('R uses LV6/11/16 gates and maximum rank three',()=>{const h=initialProgression(),p=new Progression(h);assert.equal(p.allocate('r-early','zone').reason,'Requires LV 6');p.award('to6',toLevel(6));assert.equal(p.allocate('r1','zone').rank,1);assert.equal(p.allocate('r2-early','zone').reason,'Requires LV 11');p.award('to11',toLevel(11)-toLevel(6));assert.equal(p.allocate('r2','zone').rank,2);assert.equal(p.allocate('r3-early','zone').reason,'Requires LV 16');p.award('to16',toLevel(16)-toLevel(11));assert.equal(p.allocate('r3','zone').rank,3);assert.equal(p.allocate('r4','zone').reason,'Maximum skill rank');});
test('double-tap and point exhaustion do not spend twice',()=>{const s=new Simulation();learn(s,'bash','same');learn(s,'bash','same');learn(s,'taunt','different');ticks(s,1);const e=s.drainEvents();assert.equal(e.filter(e=>e.type==='skill-upgraded').length,1);assert.deepEqual([s.state.heroProgression.skillPoints,s.state.heroProgression.ranks.bash,s.state.heroProgression.ranks.taunt],[0,1,0]);assert.equal(e.filter(e=>e.type==='rejected').length,2);});
test('malformed/unknown/stat-upgrade/XP player commands reject without mutation',()=>{const s=new Simulation(),before=structuredClone(s.state);for(const c of [{type:'learn',skill:'toString',requestId:'x'},{type:'learn',skill:'stats',requestId:'x'},{type:'learn',skill:'bash',requestId:''},{type:'learn',skill:'bash',requestId:123},{type:'xp',amount:80}])assert.equal(s.send(c),false);assert.deepEqual(s.state,before);});
test('pause and zero timeScale reject allocations; slow motion processes each request once',()=>{const s=new Simulation();s.setPaused(true);assert.equal(learn(s,'bash'),false);s.setPaused(false);s.setTimeScale(0);assert.equal(learn(s,'bash'),false);s.setTimeScale(.25);learn(s,'bash','quarter');ticks(s,120);assert.equal(s.clock.tick,30);assert.equal(s.state.heroProgression.ranks.bash,1);assert.equal(s.drainEvents().filter(e=>e.type==='skill-upgraded').length,1);});
test('level-dependent respawn uses exact fixed-clock ticks, including fractional seconds',()=>{for(let lv=1;lv<=20;lv++)assert.equal(respawnTicks(lv),150+24*(lv-1));assert.equal(respawnTicks(20),606);});
test('XP, level, points and ranks survive death, safe respawn and protection',()=>{const {s,e}=duel();s.progression.award('fixture',toLevel(3)+7);learn(s,'bash');ticks(s,1);const progression=structuredClone(s.state.heroProgression);s.hero.hp=1;e.x=860;e.damage=18;e.readyTick=0;e.strike=undefined;ticks(s,10);assert.equal(s.hero.hp,0);const deadline=s.hero.respawnTick;assert.equal(deadline-s.clock.tick,respawnTicks(3));s.setPaused(true);ticks(s,50);assert.equal(s.hero.hp,0);s.setPaused(false);ticks(s,deadline-s.clock.tick);assert.equal(s.hero.hp,s.hero.maxHp);assert.deepEqual(s.state.heroProgression,progression);assert.equal(s.hero.protectionTick,s.clock.tick+60);});
test('allocation while dead is authoritative and persists through respawn',()=>{const {s,e}=duel();s.hero.hp=1;e.x=860;e.damage=18;e.readyTick=0;e.strike=undefined;ticks(s,10);learn(s,'taunt');ticks(s,1);assert.equal(s.state.heroProgression.ranks.taunt,1);assert.equal(s.hero.hp,0);});
test('absent reward profiles award nothing despite a real enemy kill',()=>{const old=enemyXp['minion-red'];delete enemyXp['minion-red'];try{const {s,e}=duel();assert.equal(enemyXp['minion-red'],undefined);e.hp=80;s.send({type:'attack'});ticks(s,7);assert.equal(s.state.kills,1);assert.equal(s.state.gold,265);assert.deepEqual(s.state.heroProgression,initialProgression());assert.equal(s.drainEvents().filter(e=>e.type==='xp').length,0);}finally{enemyXp['minion-red']=old;}});
test('configured fixture XP goes to a participant without requiring last-hit',()=>policy(()=>{const {s,e}=duel();s.hit(s.hero,e);const ally={...e,id:'ally',kind:'minion-blue',team:'blue',damage:240};s.hit(ally,e);assert.equal(s.state.heroProgression.level,2);assert.equal(s.state.gold,265);const events=s.drainEvents();assert.equal(events.filter(e=>e.type==='xp').length,1);s.hit(ally,e);assert.equal(s.drainEvents().length,0);}));
test('no arbitrary assist radius or friendly-fire XP is invented',()=>policy(()=>{const {s,e}=duel();s.hero.x=450;const ally={...e,id:'ally',kind:'minion-blue',team:'blue',damage:240};s.hit(ally,e);assert.equal(s.state.heroProgression.xp,0);assert.equal(s.state.heroProgression.level,1);}));
test('zero-damage contact does not establish XP participation',()=>policy(()=>{const {s,e}=duel();s.hero.x=450;s.hero.damage=0;s.hit(s.hero,e);s.hit({...s.hero,id:'ally',kind:'minion-blue',damage:240},e);assert.equal(s.state.heroProgression.xp,0);assert.equal(s.state.heroProgression.level,1);}));
test('terminal state and Restart transition reject allocation and freeze progression',()=>{const s=new Simulation();s.state.bases['red-base'].hp=0;ticks(s,1);const p=structuredClone(s.state.heroProgression);assert.equal(learn(s,'bash'),false);ticks(s,50);assert.deepEqual(s.state.heroProgression,p);const n=new Simulation();n.beginRestart();assert.equal(learn(n,'bash'),false);});
test('new match resets progression and transaction ledgers repeatedly',()=>{for(let i=0;i<4;i++){const s=new Simulation();learn(s,'bash','same-ui-id');ticks(s,1);assert.equal(s.state.heroProgression.ranks.bash,1);assert.equal(s.state.heroProgression.skillPoints,0);assert.equal(s.state.heroProgression.level,1);}});
test('all known ranks spend eighteen points; undefined special stats retain the other two',()=>{const h=initialProgression(),p=new Progression(h);p.award('max',5795);for(const key of ['bash','taunt','charge','zone'])for(let i=1;i<=(key==='zone'?3:5);i++)assert.equal(p.allocate(`${key}${i}`,key).type,'skill-upgraded');assert.equal(h.skillPoints,2);assert.equal(p.allocate('stats','stats').reason,'Unknown skill');assert.equal(h.skillPoints,2);});
test('allocation and level-dependent lifecycle replay identically at 30/60 rendering FPS',()=>{const a=new Simulation(),b=new Simulation();for(const s of [a,b]){s.progression.award('explicit-test-source',toLevel(3));learn(s,'bash','q');s.send({type:'move',x:.1,y:0});}for(let i=0;i<600;i++)a.advance(1000/30);for(let i=0;i<1200;i++)b.advance(1000/60);assert.deepEqual(a.state,b.state);assert.deepEqual(a.drainEvents(),b.drainEvents());});
test('opening allocation clears only player combat intent and preserves enemy windup',()=>{const {s,e}=duel();s.state.attacking=true;s.state.move={x:1,y:0};e.strike={targetId:'guardian',atTick:9};s.hero.strike={targetId:e.id,atTick:9};s.clearHeroInput();assert.equal(s.hero.strike,undefined);assert.deepEqual(e.strike,{targetId:'guardian',atTick:9});assert.equal(s.state.attacking,false);});
