const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync,readdirSync}=require('node:fs');
const {Simulation}=require('../.test-build/simulation/Simulation.js');
const {Clock}=require('../.test-build/simulation/Clock.js');
const {blocked,move,lineOfSight}=require('../.test-build/simulation/Collision.js');
const {damageAfterArmor}=require('../.test-build/simulation/Combat.js');
const ticks=(s,n)=>{for(let i=0;i<n;i++)s.advance(1000/30);};
function duel(){const s=new Simulation();ticks(s,1);const enemy=s.state.units['red-0-0'];for(const id of Object.keys(s.state.units))if(id!=='guardian'&&id!==enemy.id)delete s.state.units[id];enemy.x=870;enemy.y=590;enemy.speed=0;enemy.damage=0;s.drainEvents();return {s,enemy};}
test('30 Hz produces identical state at 30 and 60 render FPS',()=>{const a=new Simulation(),b=new Simulation();a.send({type:'move',x:-1,y:0});b.send({type:'move',x:-1,y:0});for(let i=0;i<30;i++)a.advance(1000/30);for(let i=0;i<60;i++)b.advance(1000/60);assert.equal(a.clock.tick,30);assert.deepEqual(a.state,b.state);});
test('real delta clamp and catch-up cap prevent background replay',()=>{const c=new Clock();c.advance(60000,()=>{});assert.equal(c.tick,3);c.timeScale=2;c.advance(100,()=>{});assert.equal(c.tick,8);});
test('pause freezes clock, attacks, movement and spawn; resume discards intents',()=>{const {s}=duel();s.send({type:'move',x:1,y:0});s.send({type:'attack'});s.setPaused(true);const before=structuredClone(s.state),tick=s.clock.tick;ticks(s,300);assert.deepEqual(s.state,before);assert.equal(s.clock.tick,tick);assert.equal(s.send({type:'attack'}),false);s.setPaused(false);ticks(s,1);assert.equal(s.hero.x,before.units.guardian.x);assert.equal(s.state.attacking,false);});
test('slow motion is absolute and scales every timer',()=>{const s=new Simulation();s.setTimeScale(.25);s.setTimeScale(.25);ticks(s,120);assert.equal(s.clock.tick,30);s.setTimeScale(1);ticks(s,30);assert.equal(s.clock.tick,60);assert.throws(()=>s.setTimeScale(NaN));});
test('zero timeScale clears intents and freezes simulation',()=>{const s=new Simulation();s.send({type:'attack'});s.setTimeScale(0);assert.equal(s.send({type:"attack"}),false);ticks(s,50);assert.equal(s.clock.tick,0);assert.equal(s.state.attacking,false);});
test('movement normalizes diagonal input using simulation seconds',()=>{const s=new Simulation();s.teleportHero(450,450);s.send({type:'move',x:1,y:1});ticks(s,1);assert.ok(Math.abs(Math.hypot(s.hero.x-450,s.hero.y-450)-280/30)<1e-6);});
test('boundaries, water, bridge, structures and scenery use radius',()=>{assert.ok(blocked(10,500,20));assert.ok(blocked(960,430,20));assert.ok(!blocked(960,590,20));assert.ok(blocked(620,495,20));assert.ok(blocked(120,160,12));const u={x:600,y:600,radius:20};move(u,0,-200);assert.ok(u.y>=539);assert.ok(!blocked(u.x,u.y,u.radius));});
test('swept movement cannot tunnel through river or structures',()=>{const u={x:800,y:430,radius:20};move(u,400,0);assert.ok(u.x<=860);const wall={x:720,y:800,radius:12};move(wall,0,-200);assert.ok(wall.y>=726);});
test('line of sight rejects water, wall and scenery, accepts bridge',()=>{assert.equal(lineOfSight({x:850,y:430},{x:1060,y:430}),false);assert.equal(lineOfSight({x:720,y:640},{x:720,y:740}),false);assert.equal(lineOfSight({x:850,y:575},{x:1060,y:575}),true);});
test('commands validate payloads before mutation',()=>{const s=new Simulation();const before=structuredClone(s.state);assert.equal(s.send({type:'move',x:NaN,y:0}),false);assert.equal(s.send({type:'target',id:'guardian'}),false);assert.equal(s.send({type:'preview',key:'unknown'}),false);assert.deepEqual(s.state,before);assert.equal(s.drainEvents().length,3);});
test('basic attack winds up, applies damage once, and respects cooldown',()=>{const {s,enemy}=duel();s.send({type:'attack'});ticks(s,1);assert.equal(enemy.hp,240);ticks(s,5);assert.equal(enemy.hp,240);ticks(s,1);assert.equal(enemy.hp,160);ticks(s,16);assert.equal(enemy.hp,160);ticks(s,7);assert.equal(enemy.hp,80);});
test('target override prefers selected valid enemy',()=>{const {s,enemy}=duel();const second={...enemy,id:'second',x:880};s.state.units.second=second;s.send({type:'target',id:'second'});s.send({type:'attack'});ticks(s,7);assert.equal(second.hp,160);assert.equal(enemy.hp,240);});
test('moving target out of range cancels windup without damage',()=>{const {s,enemy}=duel();s.send({type:'attack'});ticks(s,1);enemy.x=1100;ticks(s,10);assert.equal(enemy.hp,240);assert.equal(s.hero.strike,undefined);});
test('armor clamp and damage types follow specification',()=>{assert.equal(damageAfterArmor(120,20),100);assert.equal(damageAfterArmor(80,-20),80);assert.equal(damageAfterArmor(120,20,'magic'),100);assert.equal(damageAfterArmor(120,20,'direct'),120);});
test('death removes unit, cancels targeting and rewards exactly once',()=>{const {s,enemy}=duel();enemy.hp=20;s.send({type:'attack'});ticks(s,100);const events=s.drainEvents();assert.equal(s.state.units[enemy.id],undefined);assert.equal(events.filter(e=>e.type==='death').length,1);assert.equal(events.filter(e=>e.type==='reward').length,1);assert.equal(s.state.gold,265);assert.equal(s.state.kills,1);assert.deepEqual(s.drainEvents(),[]);});
test('minion approaches, acquires Guardian, and deals armor-adjusted damage',()=>{const {s,enemy}=duel();enemy.x=1000;enemy.speed=95;enemy.damage=18;ticks(s,90);assert.ok(enemy.x<1000);assert.ok(s.hero.hp<1200);assert.equal(enemy.targetId,'guardian');});
test('hero death clears controls and respawns after five simulation seconds',()=>{const {s,enemy}=duel();s.hero.hp=1;enemy.x=860;enemy.damage=18;ticks(s,10);assert.equal(s.hero.hp,0);assert.equal(s.state.attacking,false);const at=s.hero.respawnTick;s.setPaused(true);ticks(s,300);assert.equal(s.hero.hp,0);s.setPaused(false);ticks(s,at-s.clock.tick);assert.equal(s.hero.hp,1200);assert.equal(s.hero.x,450);assert.equal(s.hero.protectionTick,s.clock.tick+60);});
test('wave schedule spawns only once and remains frozen by pause',()=>{const s=new Simulation();ticks(s,1);assert.equal(s.state.spawnedWaves,1);s.setPaused(true);ticks(s,500);assert.equal(s.state.spawnedWaves,1);s.setPaused(false);ticks(s,239);assert.equal(s.state.spawnedWaves,2);ticks(s,10);const events=s.drainEvents();assert.equal(events.filter(e=>e.type==='spawn'&&e.id.startsWith('red-')).length,6);assert.equal(events.filter(e=>e.type==='spawn'&&e.id.startsWith('blue-')).length,3);});
test('preview cooldown is authoritative and duplicate commands do not replay',()=>{const s=new Simulation();s.send({type:'preview',key:'bash'});s.send({type:'preview',key:'bash'});ticks(s,1);assert.equal(s.drainEvents().filter(e=>e.type==='preview').length,1);s.setPaused(true);const r=s.remaining('bash');ticks(s,100);assert.equal(s.remaining('bash'),r);});
test('simulation runs headlessly with no renderer or browser dependency',()=>{for(const dir of ['simulation','data'])for(const f of readdirSync(`src/${dir}`)){const source=readFileSync(`src/${dir}/${f}`,'utf8');assert.doesNotMatch(source,/from ['"]phaser|window\.|document\.|setTimeout|setInterval/);}const s=new Simulation();ticks(s,30);assert.equal(s.clock.tick,30);const layout=require('../.test-build/world/layout.js');const original=structuredClone(layout.entities);s.send({type:'move',x:1,y:0});ticks(s,30);assert.deepEqual(layout.entities,original);});


test('pause cancels pending windup; fresh attack resumes after cooldown',()=>{const {s,enemy}=duel();s.send({type:'attack'});ticks(s,1);assert.ok(s.hero.strike);s.setPaused(true);ticks(s,60);assert.equal(enemy.hp,240);s.setPaused(false);ticks(s,24);assert.equal(enemy.hp,240);s.send({type:'attack'});ticks(s,7);assert.equal(enemy.hp,160);});

test('render frame partition remains deterministic through combat, death and respawn',()=>{const a=new Simulation(),b=new Simulation();for(let i=0;i<750;i++)a.advance(1000/30);for(let i=0;i<1500;i++)b.advance(1000/60);assert.equal(a.clock.tick,750);assert.deepEqual(a.state,b.state);assert.deepEqual(a.drainEvents(),b.drainEvents());});
const place=(s,kind='wall',col=12,row=12,requestId='test')=>s.send({type:'place',kind,col,row,requestId});
test('exact initial resources and fractional income use simulation ticks',()=>{const s=new Simulation();assert.deepEqual([s.state.gold,s.state.wood,s.state.iron],[250,180,30]);ticks(s,120);assert.deepEqual([s.state.gold,s.state.wood,s.state.iron],[250,188,31]);});
test('successful wall construction charges exactly once including duplicate request replay',()=>{const s=new Simulation();place(s);place(s);ticks(s,1);assert.equal(Object.keys(s.state.structures).length,1);assert.equal(s.state.wood,155+1/15);place(s,'wall',11,12);ticks(s,1);assert.equal(Object.keys(s.state.structures).length,1);assert.equal(s.drainEvents().filter(e=>e.type==='built').length,1);});
test('placement rejects occupied, water, out of map, outside territory and spawn without deduction',()=>{const s=new Simulation();for(const [i,[c,r]] of [[12,12],[9,12],[6,12],[20,8],[-1,0],[25,12]].entries()){place(s,'wall',c,r,`p-${i}`);ticks(s,1);}assert.equal(Object.keys(s.state.structures).length,1);assert.equal(s.state.wood,155+6/15);assert.match(s.placementReason('wall',12,12),/Occupied/);});
test('unit occupancy is checked at command execution',()=>{const s=new Simulation();place(s);s.teleportHero(600,600);ticks(s,1);assert.equal(Object.keys(s.state.structures).length,0);assert.equal(s.state.wood,180+1/15);});
test('insufficient funds rejects atomically and resources never become negative',()=>{const s=new Simulation();let i=0;for(let r=7;r<17;r++)for(let c=1;c<14;c++)if(!s.placementReason('tower',c,r))place(s,'tower',c,r,`many-${i++}`);ticks(s,1);assert.equal(Object.keys(s.state.structures).length,2);assert.equal(s.state.wood,20+1/15);assert.equal(s.state.iron,10+1/120);assert.ok(s.drainEvents().some(e=>e.reason==='Not enough resources'));});
test('wall blocks immediately and grows to specified HP in two seconds',()=>{const s=new Simulation();place(s);ticks(s,1);const b=Object.values(s.state.structures)[0];assert.ok(b.hp>0&&b.hp<400);const u={x:600,y:680,radius:20};move(u,0,-180,s.state.structures);assert.ok(u.y>=644);ticks(s,60);assert.equal(b.hp,400);assert.equal(b.progress,1);assert.equal(s.drainEvents().filter(e=>e.type==='construction-complete').length,1);});
function towerDuel(){const s=new Simulation();place(s,'tower',14,12);ticks(s,151);const b=Object.values(s.state.structures)[0];for(const id of Object.keys(s.state.units))if(id!=='guardian')delete s.state.units[id];const e={...s.hero,id:'test-enemy',kind:'minion-red',team:'red',x:820,y:600,hp:240,maxHp:240,armor:0,speed:0,damage:0,range:48,strike:undefined,targetId:undefined};s.state.units[e.id]=e;b.readyTick=s.clock.tick;b.strike=undefined;s.drainEvents();return {s,b,e};}
test('tower waits five seconds then targets nearest valid enemy with exact damage/cooldown',()=>{const {s,b,e}=towerDuel();ticks(s,1);assert.equal(e.hp,222);assert.equal(b.readyTick,s.clock.tick+24);ticks(s,23);assert.equal(e.hp,222);ticks(s,1);assert.equal(e.hp,204);});
test('tower range, line of sight and target reacquisition',()=>{const {s,b,e}=towerDuel();e.x=b.x+241;ticks(s,1);assert.equal(e.hp,240);e.x=820;e.y=600;ticks(s,1);assert.equal(e.hp,222);delete s.state.units[e.id];ticks(s,30);assert.equal(b.targetId,undefined);});
test('tower cannot shoot during construction',()=>{const s=new Simulation();/* Isolate Tower activation from the new allied attackers. */for(const id of Object.keys(s.state.units))if(id.startsWith('blue-'))delete s.state.units[id];place(s,'tower',14,12);ticks(s,1);const b=Object.values(s.state.structures)[0];const enemy=s.state.units['red-0-0'];enemy.x=820;enemy.y=600;enemy.speed=0;enemy.damage=0;ticks(s,149);assert.equal(enemy.hp,240);ticks(s,1);assert.equal(enemy.hp,222);assert.equal(b.progress,1);});
test('enemy destroys structures once, removes collision, grants no reward',()=>{const {s,b,e}=towerDuel();e.x=b.x+40;e.damage=1000;e.readyTick=0;e.windupTicks=0;e.range=48;e.targetId=b.id;e.targetSinceTick=s.clock.tick;e.decisionTick=s.clock.tick+6;b.hp=1;const gold=s.state.gold;ticks(s,1);assert.equal(s.state.structures[b.id],undefined);assert.equal(blocked(b.x,b.y,0,s.state.structures),false);assert.equal(s.state.gold,gold);assert.equal(s.drainEvents().filter(v=>v.type==='death'&&v.id===b.id).length,1);});
test('construction and income obey pause/timeScale and pending placements cancel on pause',()=>{const s=new Simulation();place(s);s.setPaused(true);ticks(s,60);assert.equal(s.state.wood,180);assert.equal(Object.keys(s.state.structures).length,0);s.setPaused(false);place(s);s.setTimeScale(.25);ticks(s,120);const b=Object.values(s.state.structures)[0];assert.equal(s.clock.tick,30);assert.ok(b.progress<1);assert.equal(s.state.wood,157);s.setPaused(true);const snapshot=structuredClone(s.state);ticks(s,300);assert.deepEqual(s.state,snapshot);});
test('malformed construction commands cannot mutate state',()=>{const s=new Simulation();for(const c of [{kind:'unknown',col:1,row:1,requestId:'x'},{kind:'wall',col:NaN,row:1,requestId:'x'},{kind:'wall',col:1,row:1,requestId:''}])assert.equal(s.send({type:'place',...c}),false);assert.equal(s.state.wood,180);});
const {Economy}=require('../.test-build/simulation/Economy.js');
test('resource command ledger rejects duplicate income/rewards/debits and unaffordable purchases atomically',()=>{const s=new Simulation(),e=new Economy(s.state);assert.ok(e.apply({type:'income',tick:1}));assert.equal(e.apply({type:'income',tick:1}),false);assert.equal(e.apply({type:'income',tick:3}),false);assert.ok(e.apply({type:'minion-reward',id:'one'}));assert.equal(e.apply({type:'minion-reward',id:'one'}),false);assert.equal(s.state.gold,265);assert.ok(e.apply({type:'construction',id:'one',kind:'tower'}));assert.equal(e.apply({type:'construction',id:'one',kind:'tower'}),false);assert.ok(e.apply({type:'construction',id:'two',kind:'tower'}));const before=structuredClone(s.state);assert.equal(e.apply({type:'construction',id:'three',kind:'tower'}),false);assert.deepEqual(s.state,before);});
test('tower picks nearest target independently of Guardian selection',()=>{const {s,b,e}=towerDuel();const far={...e,id:'far',x:850};s.state.units.far=far;s.send({type:'target',id:'far'});ticks(s,1);assert.equal(e.hp,222);assert.equal(far.hp,240);});
test('construction retains damage while HP capacity grows',()=>{const s=new Simulation();place(s);ticks(s,30);const b=Object.values(s.state.structures)[0];const e={...s.hero,id:'construction-attacker',kind:'minion-red',team:'red',x:b.x+40,y:b.y,speed:0,range:48,damage:50,readyTick:0,windupTicks:0,cooldownTicks:1000,targetId:b.id,targetSinceTick:s.clock.tick,decisionTick:s.clock.tick+6};s.state.units[e.id]=e;ticks(s,31);assert.equal(b.hp,350);assert.equal(b.progress,1);});
test('tower cap rejects the 31st without spending',()=>{const s=new Simulation();for(let i=0;i<30;i++)s.state.structures[`cap-${i}`]={kind:'tower',x:-1000-i*48,y:0};assert.match(s.placementReason('tower',12,12),/limit/);});
test('competing requests for the same cell cannot charge twice',()=>{const s=new Simulation();place(s,'wall',12,12,'first');place(s,'wall',12,12,'second');ticks(s,1);assert.equal(Object.keys(s.state.structures).length,1);assert.equal(s.state.wood,155+1/15);});
test('constructed wall can be destroyed and collision is released without refund',()=>{const s=new Simulation();place(s);ticks(s,61);const b=Object.values(s.state.structures)[0];const e={...s.hero,id:'wall-attacker',kind:'minion-red',team:'red',x:b.x+40,y:b.y,speed:0,range:48,damage:1000,readyTick:0,windupTicks:0,targetId:b.id,targetSinceTick:s.clock.tick,decisionTick:s.clock.tick+6};s.state.units[e.id]=e;const gold=s.state.gold,wood=s.state.wood;ticks(s,1);assert.equal(s.state.structures[b.id],undefined);assert.equal(blocked(b.x,b.y,0,s.state.structures),false);assert.equal(s.state.gold,gold);assert.equal(s.state.wood,wood+1/15);});
test('building management remains available while Guardian is dead',()=>{const s=new Simulation();s.hero.hp=0;s.hero.respawnTick=150;place(s);s.send({type:'attack'});ticks(s,1);assert.equal(Object.keys(s.state.structures).length,1);assert.equal(s.state.attacking,false);assert.equal(s.state.wood,155+1/15);});
test('placement checks exact scenery intersection even between sample points',()=>{const layout=require('../.test-build/world/layout.js'),s=new Simulation();layout.scenery.push({kind:'bush',x:577,y:612,radius:2,height:4});try{assert.match(s.placementReason('wall',12,12),/Scenery/);}finally{layout.scenery.pop();}});

test('completed undamaged tower has exact specified HP',()=>{const s=new Simulation();place(s,'tower',14,11);ticks(s,151);assert.equal(Object.values(s.state.structures)[0].hp,650);});
