const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync,readdirSync}=require('node:fs');
const {Simulation}=require('../.test-build/simulation/Simulation.js');
const {Clock}=require('../.test-build/simulation/Clock.js');
const {blocked,move,lineOfSight}=require('../.test-build/simulation/Collision.js');
const {damageAfterArmor}=require('../.test-build/simulation/Combat.js');
const ticks=(s,n)=>{for(let i=0;i<n;i++)s.advance(1000/30);};
function duel(){const s=new Simulation();ticks(s,1);const enemy=s.state.units['red-0-0'];for(const id of Object.keys(s.state.units))if(id!=='guardian'&&id!==enemy.id)delete s.state.units[id];enemy.x=870;enemy.y=590;enemy.speed=0;enemy.damage=0;s.drainEvents();return {s,enemy};}
test('30 Hz produces identical state at 30 and 60 render FPS',()=>{const a=new Simulation(),b=new Simulation();a.send({type:'move',x:-1,y:0});b.send({type:'move',x:-1,y:0});for(let i=0;i<30;i++)a.advance(1000/30);for(let i=0;i<60;i++)b.advance(1000/60);assert.equal(a.clock.tick,30);assert.deepEqual(a.state,b.state);});
test('real delta clamp and catch-up cap prevent background replay',()=>{const c=new Clock();c.advance(60000,()=>{});assert.equal(c.tick,3);c.timeScale=2;c.advance(100,()=>{});assert.equal(c.tick,8);});
test('pause freezes clock, attacks, movement and spawn; resume discards intents',()=>{const {s}=duel();s.send({type:'move',x:1,y:0});s.send({type:'attack'});s.setPaused(true);const before=structuredClone(s.state),tick=s.clock.tick;ticks(s,300);assert.deepEqual(s.state,before);assert.equal(s.clock.tick,tick);assert.equal(s.send({type:'attack'}),false);s.setPaused(false);ticks(s,1);assert.equal(s.hero.x,before.units.guardian.x);assert.equal(s.state.attacking,false);});
test('slow motion is absolute and scales every timer',()=>{const s=new Simulation();s.setTimeScale(.25);s.setTimeScale(.25);ticks(s,120);assert.equal(s.clock.tick,30);s.setTimeScale(1);ticks(s,30);assert.equal(s.clock.tick,60);assert.throws(()=>s.setTimeScale(NaN));});
test('zero timeScale clears intents and freezes simulation',()=>{const s=new Simulation();s.send({type:'attack'});s.setTimeScale(0);assert.equal(s.send({type:"attack"}),false);ticks(s,50);assert.equal(s.clock.tick,0);assert.equal(s.state.attacking,false);});
test('movement normalizes diagonal input using simulation seconds',()=>{const s=new Simulation();s.teleportHero(450,450);s.send({type:'move',x:1,y:1});ticks(s,1);assert.ok(Math.abs(Math.hypot(s.hero.x-450,s.hero.y-450)-280/30)<1e-6);});
test('boundaries, water, bridge, structures and scenery use radius',()=>{assert.ok(blocked(10,500,20));assert.ok(blocked(960,430,20));assert.ok(!blocked(960,590,20));assert.ok(blocked(620,495,20));assert.ok(blocked(120,160,12));const u={x:600,y:600,radius:20};move(u,0,-200);assert.ok(u.y>=539);assert.ok(!blocked(u.x,u.y,u.radius));});
test('swept movement cannot tunnel through river or structures',()=>{const u={x:800,y:430,radius:20};move(u,400,0);assert.ok(u.x<=860);const wall={x:720,y:800,radius:12};move(wall,0,-200);assert.ok(wall.y>=726);});
test('line of sight rejects water, wall and scenery, accepts bridge',()=>{assert.equal(lineOfSight({x:850,y:430},{x:1060,y:430}),false);assert.equal(lineOfSight({x:720,y:640},{x:720,y:740}),false);assert.equal(lineOfSight({x:850,y:575},{x:1060,y:575}),true);});
test('commands validate payloads before mutation',()=>{const s=new Simulation();const before=structuredClone(s.state);assert.equal(s.send({type:'move',x:NaN,y:0}),false);assert.equal(s.send({type:'target',id:'guardian'}),false);assert.equal(s.send({type:'preview',key:'unknown'}),false);assert.deepEqual(s.state,before);assert.equal(s.drainEvents().length,3);});
test('basic attack winds up, applies damage once, and respects cooldown',()=>{const {s,enemy}=duel();s.send({type:'attack'});ticks(s,1);assert.equal(enemy.hp,240);ticks(s,5);assert.equal(enemy.hp,240);ticks(s,1);assert.equal(enemy.hp,160);ticks(s,16);assert.equal(enemy.hp,160);ticks(s,7);assert.equal(enemy.hp,80);});
test('target override prefers selected valid enemy',()=>{const {s,enemy}=duel();const second={...enemy,id:'second',x:880};s.state.units.second=second;s.send({type:'target',id:'second'});s.send({type:'attack'});ticks(s,7);assert.equal(second.hp,160);assert.equal(enemy.hp,240);});
test('moving target out of range cancels windup without damage',()=>{const {s,enemy}=duel();s.send({type:'attack'});ticks(s,1);enemy.x=1100;ticks(s,10);assert.equal(enemy.hp,240);assert.equal(s.hero.strike,undefined);});
test('armor clamp and damage types follow specification',()=>{assert.equal(damageAfterArmor(120,20),100);assert.equal(damageAfterArmor(80,-20),80);assert.equal(damageAfterArmor(120,20,'magic'),100);assert.equal(damageAfterArmor(120,20,'direct'),120);});
test('death removes unit, cancels targeting and rewards exactly once',()=>{const {s,enemy}=duel();enemy.hp=20;s.send({type:'attack'});ticks(s,100);const events=s.drainEvents();assert.equal(s.state.units[enemy.id],undefined);assert.equal(events.filter(e=>e.type==='death').length,1);assert.equal(events.filter(e=>e.type==='reward').length,1);assert.equal(s.state.gold,265);assert.equal(s.state.kills,1);assert.deepEqual(s.drainEvents(),[]);});
test('minion approaches, acquires Guardian, and deals armor-adjusted damage',()=>{const {s,enemy}=duel();enemy.x=1000;enemy.speed=95;enemy.damage=18;ticks(s,90);assert.ok(enemy.x<1000);assert.ok(s.hero.hp<1200);assert.equal(enemy.targetId,'guardian');});
test('hero death clears controls and respawns after five simulation seconds',()=>{const {s,enemy}=duel();s.hero.hp=1;enemy.x=860;enemy.damage=18;ticks(s,10);assert.equal(s.hero.hp,0);assert.equal(s.state.attacking,false);const at=s.hero.respawnTick;s.setPaused(true);ticks(s,300);assert.equal(s.hero.hp,0);s.setPaused(false);ticks(s,at-s.clock.tick);assert.equal(s.hero.hp,1200);assert.equal(s.hero.x,450);assert.equal(s.hero.protectionTick,s.clock.tick+60);});
test('wave schedule spawns only once and remains frozen by pause',()=>{const s=new Simulation();ticks(s,1);assert.equal(s.state.spawnedWaves,1);s.setPaused(true);ticks(s,500);assert.equal(s.state.spawnedWaves,1);s.setPaused(false);ticks(s,239);assert.equal(s.state.spawnedWaves,2);ticks(s,10);assert.equal(s.drainEvents().filter(e=>e.type==='spawn').length,6);});
test('preview cooldown is authoritative and duplicate commands do not replay',()=>{const s=new Simulation();s.send({type:'preview',key:'bash'});s.send({type:'preview',key:'bash'});ticks(s,1);assert.equal(s.drainEvents().filter(e=>e.type==='preview').length,1);s.setPaused(true);const r=s.remaining('bash');ticks(s,100);assert.equal(s.remaining('bash'),r);});
test('simulation runs headlessly with no renderer or browser dependency',()=>{for(const dir of ['simulation','data'])for(const f of readdirSync(`src/${dir}`)){const source=readFileSync(`src/${dir}/${f}`,'utf8');assert.doesNotMatch(source,/from ['"]phaser|window\.|document\.|setTimeout|setInterval/);}const s=new Simulation();ticks(s,30);assert.equal(s.clock.tick,30);const layout=require('../.test-build/world/layout.js');const original=structuredClone(layout.entities);s.send({type:'move',x:1,y:0});ticks(s,30);assert.deepEqual(layout.entities,original);});


test('pause cancels pending windup; fresh attack resumes after cooldown',()=>{const {s,enemy}=duel();s.send({type:'attack'});ticks(s,1);assert.ok(s.hero.strike);s.setPaused(true);ticks(s,60);assert.equal(enemy.hp,240);s.setPaused(false);ticks(s,24);assert.equal(enemy.hp,240);s.send({type:'attack'});ticks(s,7);assert.equal(enemy.hp,160);});

test('render frame partition remains deterministic through combat, death and respawn',()=>{const a=new Simulation(),b=new Simulation();for(let i=0;i<750;i++)a.advance(1000/30);for(let i=0;i<1500;i++)b.advance(1000/60);assert.equal(a.clock.tick,750);assert.deepEqual(a.state,b.state);assert.deepEqual(a.drainEvents(),b.drainEvents());});
