import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const variant=process.env.VERIFICATION_VARIANT||'development',url=process.env.PROTOTYPE_URL||'http://127.0.0.1:5180/';
const dir=`docs/screenshots/phase1d/${variant}`;await mkdir(dir,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:960,height:540},hasTouch:true});
const checks=[],errors=[],evidence={},lifecycle=[];let closing=false;
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});page.on('crash',()=>errors.push('Renderer crash'));browser.on('disconnected',()=>lifecycle.push({expected:closing}));
function check(ok,name){checks.push({name,passed:!!ok});if(!ok)throw new Error(name);console.log(`PASS ${name}`);}
async function click(x,y){const r=await page.locator('canvas').boundingBox();await page.mouse.click(r.x+x*r.width/960,r.y+y*r.height/540);}
async function state(){return page.evaluate(()=>{const b=window.kingdomGame.scene.getScene('Battle'),s=b.simulation,h=window.kingdomGame.scene.getScene('HUD');return {tick:s.clock.tick,state:s.state,stats:s.navigation.stats,paused:s.clock.paused,result:h.results.visible,title:h.resultTitle.text,baseText:h.baseText.text,listeners:Object.fromEntries(['cast','stick','pause-visual','poststep','simulation-event'].map(n=>[n,window.kingdomGame.events.listenerCount(n)])),baseBars:Object.values(s.state.bases).map(u=>({id:u.id,hp:u.hp,width:b.hpBars.get(u.id)?.bar.width,expected:b.hpBars.get(u.id)?.width*u.hp/u.maxHp,visible:b.visuals.get(u.id)?.visible,map:h.unitDots.get(u.id)?.visible}))};});}
async function installRecord(){await page.evaluate(()=>{window.matchEvents=[];window.frameTimes=[];window.updateTimes=[];window.sampleLast=performance.now();window.maxUnits=0;window.maxEventQueue=0;const b=window.kingdomGame.scene.getScene('Battle'),original=b.update;b.update=function(...args){const t=performance.now();try{return original.apply(this,args);}finally{window.updateTimes.push(performance.now()-t);}};window.matchRecord=e=>{const s=window.kingdomGame.scene.getScene('Battle').simulation;window.matchEvents.push({...e,tick:s.clock.tick,hp:(s.state.units[e.id]??s.state.bases[e.id])?.hp});};window.kingdomGame.events.on('simulation-event',window.matchRecord);window.matchFrame=()=>{const now=performance.now();window.frameTimes.push(now-window.sampleLast);window.sampleLast=now;const s=window.kingdomGame.scene.getScene('Battle').simulation;window.maxUnits=Math.max(window.maxUnits,Object.keys(s.state.units).length);window.maxEventQueue=Math.max(window.maxEventQueue,s.events.length);};window.kingdomGame.events.on('poststep',window.matchFrame);});}
async function takeEvents(){return page.evaluate(()=>{const percentile=(a,p)=>{const s=[...a].sort((a,b)=>a-b);return s[Math.min(s.length-1,Math.floor(s.length*p))];};return {events:window.matchEvents,maxUnits:window.maxUnits,maxEventQueue:window.maxEventQueue,frames:window.frameTimes.length,frameMedian:percentile(window.frameTimes,.5),frameP95:percentile(window.frameTimes,.95),updateMedian:percentile(window.updateTimes,.5),updateP95:percentile(window.updateTimes,.95)};});}
async function restart(){await page.evaluate(()=>window.priorMatch=window.kingdomGame.scene.getScene('Battle').simulation);await click(480,350);await page.waitForFunction(()=>{const b=window.kingdomGame.scene.getScene('Battle');return window.visualReady&&b.simulation!==window.priorMatch&&window.kingdomGame.scene.isActive('HUD');});return state();}
async function attack(){const p=await page.evaluate(()=>{const a=window.kingdomGame.scene.getScene('HUD').abilities[4];return {x:a.x,y:a.y};});await click(p.x,p.y);}
async function win(){await attack();await page.keyboard.down('d');await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').hero.x>=1480,null,{timeout:20000});await page.keyboard.up('d');await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.state.bases['red-base'].hp<3000,null,{timeout:20000});await page.screenshot({path:`${dir}/enemy-base-damage.png`});await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.state.match.phase==='victory',null,{timeout:90000});await page.waitForFunction(()=>window.kingdomGame.scene.getScene('HUD').results.visible);}
try{
 await page.goto(url);await page.waitForFunction(()=>window.visualReady&&window.kingdomGame.scene.isActive('HUD'));await installRecord();
 const initial=await state();evidence.initial=initial;check(initial.state.match.phase==='playing'&&Object.values(initial.state.bases).every(b=>b.hp===3000),'Fresh normal match starts with both authoritative bases');
 const build=await page.evaluate(()=>{const u=window.kingdomGame.scene.getScene('HUD').utilities[0];return {x:u.x,y:u.y};});await click(build.x,build.y);await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').buildingMode);await click(352,371);const cell=await page.evaluate(()=>{const b=window.kingdomGame.scene.getScene('Battle');return {x:600-b.cameras.main.scrollX,y:432-b.cameras.main.scrollY};});await click(cell.x,cell.y);await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').placement?.col===12);await click(432,470);await page.waitForFunction(()=>!!window.kingdomGame.scene.getScene('Battle').simulation.state.structures['built-ui-1']);await click(552,470);check((await state()).state.structures['built-ui-1'].kind==='wall','Actual Build UI constructs a defense during normal play');
 await click(770,46);await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.clock.paused);const paused=await state();await page.waitForTimeout(200);check(JSON.stringify((await state()).state)===JSON.stringify(paused.state)&&(await state()).tick===paused.tick,'Pause freezes the complete active match');await click(480,300);
 await page.setViewportSize({width:844,height:390});await page.waitForTimeout(100);
 const rect=await page.locator('canvas').boundingBox(),cdp=await page.context().newCDPSession(page),pt=(x,y,id)=>({x:rect.x+x/960*rect.width,y:rect.y+y/540*rect.height,id,radiusX:8,radiusY:8});const ap=await page.evaluate(()=>{const a=window.kingdomGame.scene.getScene('HUD').abilities[4];return {x:a.x,y:a.y};});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pt(104,447,1)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[pt(138,447,1)]});const touchBefore=await state();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pt(138,447,1),pt(ap.x,ap.y,2)]});await page.waitForFunction(t=>window.kingdomGame.scene.getScene('Battle').simulation.clock.tick>=t+5,touchBefore.tick);check((await state()).state.units.guardian.x>touchBefore.state.units.guardian.x&&await page.evaluate(()=>window.kingdomGame.scene.getScene('HUD').abilities[4].pressed),'844×390 actual multitouch joystick and Attack work together');await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.screenshot({path:`${dir}/mobile-active-844x390.png`});await page.setViewportSize({width:960,height:540});
 await win();evidence.victory={snapshot:await state(),record:await takeEvents()};
 check(evidence.victory.snapshot.state.bases['red-base'].hp===0&&evidence.victory.snapshot.title==='VICTORY'&&evidence.victory.record.events.some(e=>e.type==='damage'&&e.id==='red-base'&&e.sourceId==='guardian'),'Normal movement/Attack destroys full-HP enemy base and shows Victory');
 check(evidence.victory.record.events.some(e=>e.type==='damage'&&e.sourceId.startsWith('blue-')),'Approved allied minions advance and fight in the normal victory match');
 check(evidence.victory.snapshot.baseBars.every(b=>b.width===b.expected&&b.visible===(b.hp>0)&&b.map===(b.hp>0)),'Base HP, world bars, sprites and minimap synchronize with destruction');
 await page.screenshot({path:`${dir}/victory-960x540.png`});await page.setViewportSize({width:844,height:390});await page.waitForTimeout(100);await page.screenshot({path:`${dir}/victory-844x390.png`});
 check(await page.evaluate(()=>{const h=window.kingdomGame.scene.getScene('HUD'),scale=window.kingdomGame.canvas.getBoundingClientRect().height/540;return h.restartHit.displayHeight*scale>=48&&h.results.visible&&h.restartHit.x-h.restartHit.displayWidth/2>=0&&h.restartHit.x+h.restartHit.displayWidth/2<=960;}),'Mobile result overlay and Restart meet touch size and viewport bounds');
 const terminal=await state();await click(ap.x,ap.y);await click(build.x,build.y);await page.mouse.move(rect.x+104*rect.width/960,rect.y+447*rect.height/540);await page.mouse.down();await page.mouse.move(rect.x+150*rect.width/960,rect.y+447*rect.height/540);await page.mouse.up();await page.keyboard.press('Space');await page.keyboard.press('w');await page.waitForTimeout(150);check(JSON.stringify((await state()).state)===JSON.stringify(terminal.state)&&(await state()).tick===terminal.tick,'Results overlay blocks joystick, Attack, Build, pause and keyboard gameplay');
 await page.setViewportSize({width:960,height:540});evidence.restart=await restart();check(evidence.restart.state.match.phase==='playing'&&!evidence.restart.result&&evidence.restart.state.gold===250&&evidence.restart.state.units.guardian.hp===1200&&Object.keys(evidence.restart.state.structures).length===0&&Object.values(evidence.restart.state.bases).every(b=>b.hp===3000)&&evidence.restart.state.spawnedWaves<=1&&evidence.restart.stats.plans<20&&evidence.restart.state.attacking===false,'Actual Restart restores HP/resources/waves/structures/routes/controls and removes results');
 // From this fresh restart, take no attack/movement/build actions: unchanged waves decide the match.
 await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.state.bases['blue-base'].hp<3000,null,{timeout:150000});await page.screenshot({path:`${dir}/allied-base-damage.png`});console.log('Normal defeat: allied base is taking authoritative damage');
 await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.state.match.phase==='defeat',null,{timeout:300000});await page.waitForFunction(()=>window.kingdomGame.scene.getScene('HUD').results.visible);evidence.defeat={snapshot:await state(),record:await takeEvents()};
 check(evidence.defeat.snapshot.state.bases['blue-base'].hp===0&&evidence.defeat.snapshot.title==='DEFEAT','Fresh restarted match reaches normal Defeat without combat-stat or state shortcuts');await page.screenshot({path:`${dir}/defeat-960x540.png`});await page.setViewportSize({width:844,height:390});await page.waitForTimeout(100);await page.screenshot({path:`${dir}/defeat-844x390.png`});await page.setViewportSize({width:960,height:540});
 evidence.restartAgain=await restart();check(JSON.stringify(evidence.restartAgain.listeners)===JSON.stringify(initial.listeners)&&evidence.restartAgain.state.match.phase==='playing'&&!evidence.restartAgain.result&&evidence.restartAgain.state.bases['blue-base'].hp===3000,'Repeated UI Restart restores playable state without duplicated listeners');await win();evidence.secondVictory={snapshot:await state(),record:await takeEvents()};check(evidence.secondVictory.snapshot.state.match.phase==='victory','Another full normal match ends after repeated Restart');
 check(evidence.secondVictory.record.maxUnits<=13&&evidence.secondVictory.record.maxEventQueue===0&&evidence.secondVictory.snapshot.stats.maxPlansPerTick<=2&&evidence.secondVictory.snapshot.stats.maxExpandedPerPlan<=960,'Normal matches keep units/event queues/navigation work bounded');
 check(evidence.secondVictory.record.events.filter(e=>e.type==='match-end').length===3,'Exactly one terminal event per each of three normal matches');check(errors.length===0,'No missing assets, console or page errors');
}catch(e){errors.push(e.stack||String(e));try{evidence.failure=await state();await page.screenshot({path:`${dir}/failure.png`});}catch{}}
finally{closing=true;await browser.close();await writeFile(`docs/phase1d-verification-${variant}.json`,JSON.stringify({url,checks,errors,lifecycle,evidence},null,2));}
console.log(JSON.stringify({url,checks:checks.length,errors},null,2));if(errors.length)process.exitCode=1;
