import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {clickGame,clickSkillControl} from './browser-coordinates.mjs';
const variant=process.env.VERIFICATION_VARIANT||'development',url=process.env.PROTOTYPE_URL||'http://127.0.0.1:5180/?encounter=prototype',root=process.env.EVIDENCE_ROOT||'docs/phase2b';
const dir=`${root}/screenshots/${variant}`;await mkdir(dir,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:960,height:540},hasTouch:true}),checks=[],errors=[],evidence={};
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
const click=(x,y)=>clickGame(page,x,y);
async function painted(){const frame=await page.evaluate(()=>window.kingdomGame.loop.frame);await page.waitForFunction(frame=>window.kingdomGame.loop.frame>frame+1,frame);}
const check=(ok,name)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);console.log('PASS '+name);};
async function snap(){return page.evaluate(()=>{const b=window.kingdomGame.scene.getScene('Battle'),s=b.simulation,h=window.kingdomGame.scene.getScene('HUD');return {tick:s.clock.tick,hero:s.hero,progression:s.state.heroProgression,skills:s.state.skills,units:s.state.units,match:s.state.match,xpText:h.xpText.text,levelText:h.levelText.text,listeners:Object.fromEntries(['cast','skill-aim','simulation-event','poststep'].map(k=>[k,window.kingdomGame.events.listenerCount(k)])),events:window.skillEvents};});}
async function ready(){await page.waitForFunction(()=>window.visualReady&&window.kingdomGame.scene.getScene('HUD').skillPanel&&window.kingdomGame.scene.getScene('Battle').simulation.state.units['red-0-0']);await page.evaluate(()=>{window.skillEvents=[];window.kingdomGame.events.on('simulation-event',e=>window.skillEvents.push({...e,tick:window.kingdomGame.scene.getScene('Battle').simulation.clock.tick}));});}
async function learn(skill){const previous=await page.evaluate(skill=>{const p=window.kingdomGame.scene.getScene('Battle').simulation.state.heroProgression;return skill==='fortitude'?p.fortitude:p.ranks[skill];},skill);await clickSkillControl(page,'open');await page.waitForFunction(()=>window.kingdomGame.scene.getScene('HUD').skillPanel.visible);await painted();await clickSkillControl(page,skill);await page.waitForFunction(({skill,previous})=>{const p=window.kingdomGame.scene.getScene('Battle').simulation.state.heroProgression;return (skill==='fortitude'?p.fortitude:p.ranks[skill])>previous;},{skill,previous});await clickSkillControl(page,'close');await page.waitForFunction(()=>!window.kingdomGame.scene.getScene('HUD').skillPanel.visible);if(skill!=='fortitude')await page.waitForFunction(skill=>!window.kingdomGame.scene.getScene('HUD').abilities.find(a=>a.id===skill).disabled,skill);}
async function ability(skill){await painted();await page.waitForFunction(skill=>!window.kingdomGame.scene.getScene('HUD').abilities.find(a=>a.id===skill).disabled,skill);const a=await page.evaluate(skill=>{const a=window.kingdomGame.scene.getScene('HUD').abilities.find(a=>a.id===skill);return {x:a.x,y:a.y};},skill);await click(a.x,a.y);}
async function restart(){await page.evaluate(()=>window.priorSkills=window.kingdomGame.scene.getScene('Battle').simulation);await click(480,350);await page.waitForFunction(()=>window.visualReady&&window.kingdomGame.scene.getScene('Battle').simulation!==window.priorSkills&&window.kingdomGame.scene.getScene('HUD').skillPanel);}
async function joystickTo(x,y){const input=await page.context().newCDPSession(page),r=await page.locator('canvas').boundingBox(),point=(dx=0,dy=0)=>({id:9,x:r.x+(104+dx)*r.width/960,y:r.y+(447+dy)*r.height/540,radiusX:4,radiusY:4,force:1});await input.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point()]});const initial=(await snap()).hero,ix=x-initial.x,iy=y-initial.y,len=Math.hypot(ix,iy);if(len>4){await input.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point(ix/len*35,iy/len*35)]});await page.waitForFunction(()=>{const b=window.kingdomGame.scene.getScene('Battle');return Math.hypot(b.stick.x,b.stick.y)>.1;});}for(let i=0;i<60;i++){const h=(await snap()).hero,dx=x-h.x,dy=y-h.y,n=Math.hypot(dx,dy);(evidence.joystickRoute??=[]).push({target:{x,y},i,hero:{x:h.x,y:h.y},n,input:await page.evaluate(()=>{const b=window.kingdomGame.scene.getScene('Battle'),h=window.kingdomGame.scene.getScene('HUD');return {stick:b.stick,move:b.simulation.state.move,pointer:h.stickPointer};})});if(n<4)break;const strength=Math.min(.8,n/(n<60?300:150));await input.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point(dx/n*35*strength,dy/n*35*strength)]});await page.waitForTimeout(100);}await input.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point()]});await page.waitForFunction(()=>{const b=window.kingdomGame.scene.getScene('Battle');return Math.hypot(b.stick.x,b.stick.y)<.01;});await input.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>window.kingdomGame.scene.getScene('HUD').stickPointer===null);await input.detach();await painted();const h=(await snap()).hero;if(Math.hypot(x-h.x,y-h.y)>8)throw Error('Virtual joystick flank waypoint not reached');}
async function win(){await ability('attack');const h=(await snap()).hero;await joystickTo(h.x<860?820:h.x,575);await page.keyboard.down('d');await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').hero.x>=1480,null,{timeout:30000});await page.keyboard.up('d');await page.waitForFunction(()=>window.kingdomGame.scene.getScene('HUD').results.visible,null,{timeout:90000});}

try{
 await page.goto(url);await ready();const initial=await snap();await learn('bash');await ability('bash');await page.waitForFunction(()=>window.skillEvents.some(e=>e.type==='rejected'&&e.reason.includes('No legal target')));evidence.normalInvalidQ=await snap();check(evidence.normalInvalidQ.skills.ready.bash===0,'Normal out-of-range Q rejects with feedback and no cooldown spend');await page.screenshot({path:dir+'/normal-invalid-q.png'});
 await page.keyboard.down('d');await page.waitForFunction(()=>{const s=window.kingdomGame.scene.getScene('Battle').simulation;return Object.values(s.state.units).some(u=>s.skills.legalTarget(u));},null,{timeout:20000});await page.keyboard.up('d');
 evidence.normalBeforeQ=await snap();await page.screenshot({path:`${dir}/normal-before-q.png`});await ability('bash');
 await page.waitForFunction(()=>window.skillEvents.some(e=>e.type==='status'&&e.status==='stun'),null,{timeout:5000});evidence.normalAfterQ=await snap();await page.screenshot({path:`${dir}/normal-after-q.png`});
 check(evidence.normalAfterQ.events.some(e=>e.type==='damage'&&e.castId&&e.raw===80)&&evidence.normalAfterQ.skills.ready.bash>evidence.normalAfterQ.tick,'Normal learned Q causes approved physical damage, stun and authoritative cooldown');
 await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.state.heroProgression.level>=2,null,{timeout:30000});evidence.normalLevel2=await snap();
 check(evidence.normalLevel2.hero.maxHp>=1260&&evidence.normalLevel2.hero.damage>=83&&evidence.normalLevel2.levelText===`LV ${evidence.normalLevel2.progression.level}`,'Ordinary combat XP levels up, grants points and updates derived stats/HUD');
 check(evidence.normalLevel2.events.some(e=>e.type==='death'&&e.sourceId.startsWith('blue-')&&evidence.normalLevel2.events.some(x=>x.type==='xp'&&x.sourceId.includes(`:${e.id}:`)&&x.amount===60)),'An allied minion last hit grants eligible Guardian60 XP in untouched gameplay');
 await learn('charge');

 // Real controls approach an unblocked flank; no state/stat/spawn mutation.
 async function normalAim(){return page.evaluate(()=>{const s=window.kingdomGame.scene.getScene('Battle').simulation,h=s.hero;const candidates=Object.values(s.state.units).filter(u=>u.hp>40&&s.skills.legalTarget(u,144)).sort((a,b)=>b.hp-a.hp||Math.hypot(a.x-h.x,a.y-h.y)-Math.hypot(b.x-h.x,b.y-h.y));const target=candidates.find(t=>Object.values(s.state.units).filter(u=>u!==h&&u!==t&&u.hp>0&&(u.team===h.team||u.hp<=40)).every(u=>{const dx=t.x-h.x,dy=t.y-h.y,a=dx*dx+dy*dy,x=h.x-u.x,y=h.y-u.y,r=h.radius+u.radius,b=x*dx+y*dy,c=x*x+y*y-r*r,disc=b*b-a*c;if(b>=0||disc<0)return true;const entry=c<=1e-8?0:(-b-Math.sqrt(disc))/a;return entry>Math.max(0,1-(h.radius+t.radius)/Math.sqrt(a))+1e-7;}));return target?{x:target.x-h.x,y:(target.y-h.y)*.72}:null;});}

 await joystickTo(1220,490);check((await snap()).hero.x>1210,'Actual virtual joystick moves around allied crowd to a clear Charge flank');let aim=await normalAim();
 if(!aim)throw Error('Normal Charge needs a clear enemy approach; capture crowd evidence');evidence.normalBeforeE=await snap();await page.screenshot({path:dir+'/normal-before-e.png'});await dragCharge(aim.x,aim.y);
 evidence.normalCharge=await snap();await page.screenshot({path:dir+'/normal-after-e.png'});check(evidence.normalCharge.events.some(e=>e.type==='cast-accepted'&&e.skill==='charge')&&evidence.normalCharge.events.some(e=>e.type==='status'&&e.status==='slow')&&evidence.normalCharge.events.some(e=>e.type==='damage'&&e.castId&&e.raw===40),'Normal learned E hits an actual enemy once and applies Slow');
 await ability('attack');await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.state.heroProgression.level>=3,null,{timeout:25000});await learn('taunt');evidence.normalLearnedQWE=await snap();
 check(Object.values(evidence.normalLearnedQWE.progression.ranks).slice(0,3).every(r=>r===1)&&evidence.normalLearnedQWE.progression.skillPoints===evidence.normalLearnedQWE.progression.level-3,'Q/W/E learned through real XP and legal Skill Points');
 const close=await page.evaluate(()=>{const s=window.kingdomGame.scene.getScene('Battle').simulation,h=s.hero,t=Object.values(s.state.units).filter(u=>u.team==='red'&&u.hp>80).sort((a,b)=>Math.hypot(a.x-h.x,a.y-h.y)-Math.hypot(b.x-h.x,b.y-h.y))[0];return t?{distance:Math.hypot(t.x-h.x,t.y-h.y),dx:t.x-h.x,dy:t.y-h.y}:null;});if(!close)throw Error('Normal W requires a living enemy before the final allied kill');if(close.distance>42){const keys=[Math.abs(close.dx)>2?(close.dx>0?'d':'a'):null,Math.abs(close.dy)>2?(close.dy>0?'s':'w'):null].filter(Boolean);for(const k of keys)await page.keyboard.down(k);await page.waitForFunction(()=>{const s=window.kingdomGame.scene.getScene('Battle').simulation;return Object.values(s.state.units).some(u=>u.team==='red'&&u.hp>80&&Math.hypot(u.x-s.hero.x,u.y-s.hero.y)<=42);},null,{timeout:10000});for(const k of keys)await page.keyboard.up(k);await painted();}
 await ability('taunt');await page.waitForFunction(()=>window.skillEvents.some(e=>e.type==='status'&&e.status==='taunt'),null,{timeout:5000});evidence.normalTaunt=await snap();await page.screenshot({path:`${dir}/normal-taunt.png`});check(evidence.normalTaunt.events.some(e=>e.type==='status'&&e.status==='taunt'),'Normal learned W redirects actual enemy units');await page.waitForFunction(tick=>window.skillEvents.some(e=>e.type==='damage'&&e.id==='guardian'&&e.amount>0&&e.tick>tick),evidence.normalTaunt.tick,{timeout:5000});evidence.normalTauntDamage=await snap();check(evidence.normalTauntDamage.hero.hp/evidence.normalTauntDamage.hero.maxHp<evidence.normalTaunt.hero.hp/evidence.normalTaunt.hero.maxHp,'Taunted enemies still inflict real damage on Guardian');
 await win();evidence.normalVictory=await snap();await page.screenshot({path:`${dir}/normal-victory.png`});check(evidence.normalVictory.match.phase==='victory'&&evidence.normalVictory.progression.level>=3,'Normal match with real progression and skills reaches Victory');
 const xp=evidence.normalVictory.events.filter(e=>e.type==='xp');check(xp.every(e=>e.amount===60)&&new Set(xp.map(e=>e.sourceId)).size===xp.length,'Normal XP events remain life-scoped, correct and exactly once');
 await restart();evidence.restart=await snap();check(evidence.restart.progression.level===1&&evidence.restart.progression.skillPoints===1&&evidence.restart.hero.maxHp===1200&&evidence.restart.skills.zones.length===0&&Object.values(evidence.restart.skills.ready).every(t=>t===0),'UI Restart clears progression, casts, statuses and cooldowns');
 // Supplemental R/high-level fixture, explicitly not ordinary progression.
 await page.evaluate(()=>{const s=window.kingdomGame.scene.getScene('Battle').simulation;s.progression.award('supplemental-r-lv6',650);s.state.spawnedWaves=2;const a=Object.values(s.state.units).find(u=>u.kind==='minion-blue');Object.assign(s.hero,{x:750,y:575});Object.assign(a,{x:710,y:575,speed:0,damage:0,targetId:undefined,strike:undefined});s.state.units={guardian:s.hero,[a.id]:a};});await learn('zone');await ability('zone');await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.state.skills.zones.length===1);evidence.fixtureZone=await snap();await page.screenshot({path:`${dir}/supplemental-zone.png`});
 const ally=Object.values(evidence.fixtureZone.units).find(u=>u.kind==='minion-blue');check(evidence.fixtureZone.hero.shield.remaining===120&&ally.shield.remaining===72&&ally.armor===10,'Supplemental R grants120 hero /72 minion shield and10 aura armor');
 await page.evaluate(()=>{const s=window.kingdomGame.scene.getScene('Battle').simulation,a=Object.values(s.state.units).find(u=>u.kind==='minion-blue');s.state.units['red-zone-fixture']={...a,id:'red-zone-fixture',kind:'minion-red',team:'red',x:790,y:575,damage:18,readyTick:0,targetId:undefined,strike:undefined,shield:undefined,statuses:[],armor:0,baseArmor:0};});await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').hero.shield.remaining<120);evidence.fixtureShieldDamage=await snap();check(evidence.fixtureShieldDamage.hero.hp===evidence.fixtureZone.hero.hp&&evidence.fixtureShieldDamage.events.some(e=>e.type==='damage'&&e.id==='guardian'&&e.absorbed>0&&e.amount===0),'Supplemental R shield absorbs actual minion damage without healing HP');
 await page.setViewportSize({width:844,height:390});await page.screenshot({path:`${dir}/supplemental-zone-mobile.png`});
 await page.keyboard.down('a');await page.keyboard.down('s');await page.waitForTimeout(1100);await page.keyboard.up('a');await page.keyboard.up('s');const moved=await snap();check(moved.skills.zones[0].x===evidence.fixtureZone.skills.zones[0].x&&moved.hero.x<evidence.fixtureZone.hero.x-192&&moved.hero.armor===30,'Guardian moves out while zone stays fixed and aura removes immediately');
 await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').simulation.state.skills.zones.length===0);check((await snap()).hero.shield===undefined,'Zone expiry removes remaining shields without refill');

 // Supplemental LV20/Fortitude/collision/input/lifecycle; existing minion profile only.
 await page.evaluate(()=>window.kingdomGame.scene.getScene('Battle').simulation.progression.award('supplemental-lv20',5145));await learn('charge');await learn('taunt');await learn('fortitude');await learn('fortitude');evidence.fixtureFortitude=await snap();check(evidence.fixtureFortitude.progression.level===20&&evidence.fixtureFortitude.progression.fortitude===2&&evidence.fixtureFortitude.hero.maxHp===2574,'Supplemental LV20 Fortitude ranks use existing allocation UI and additive HP');await clickSkillControl(page,'open');await painted();await page.screenshot({path:dir+'/supplemental-fortitude-mobile.png'});await clickSkillControl(page,'close');await painted();
 async function collisionFixture(kind){await page.evaluate(kind=>{const s=window.kingdomGame.scene.getScene('Battle').simulation,a=Object.values(s.state.units).find(u=>u.kind==='minion-blue');s.clearHeroInput();s.state.skills.cast=undefined;s.state.skills.ready.charge=0;s.state.skills.lockTick=0;s.state.structures={};Object.assign(s.hero,{x:800,y:575});s.state.units={guardian:s.hero};if(kind==='enemy'||kind==='ally'){const u={...a,id:(kind==='enemy'?'red-':'blue-')+'collision-'+kind,kind:kind==='enemy'?'minion-red':'minion-blue',team:kind==='enemy'?'red':'blue',x:700,y:575,hp:240,maxHp:240,armor:0,baseArmor:0,radius:12,speed:0,damage:0,range:48,cooldownTicks:30,windupTicks:9,readyTick:0,protectionTick:0,targetId:undefined,strike:undefined,shield:undefined,statuses:[]};s.state.units[u.id]=u;}if(kind==='wall')s.state.structures.wall={id:'wall',kind:'wall',team:'red',x:696,y:552,col:14,row:11,hp:400,maxHp:400,armor:0,radius:24,speed:0,damage:0,range:0,cooldownTicks:24,windupTicks:0,readyTick:0,protectionTick:0,startTick:-60,completeTick:0,progress:1,constructionDamage:0};if(kind==='water'){s.hero.x=1065;s.hero.y=500;}if(kind==='bridge'){s.hero.x=960;s.hero.y=590;}},kind);await painted();}
 async function dragCharge(dx,dy=0,offset={x:7,y:11}){const a=await page.evaluate(()=>{const a=window.kingdomGame.scene.getScene('HUD').abilities.find(a=>a.id==='charge'),r=window.kingdomGame.canvas.getBoundingClientRect();return {x:a.x,y:a.y,rect:{x:r.x,y:r.y,width:r.width,height:r.height}};});const input=await page.context().newCDPSession(page),point=f=>({id:7,x:a.rect.x+(a.x+offset.x+dx*f)*a.rect.width/960,y:a.rect.y+(a.y+offset.y+dy*f)*a.rect.height/540,radiusX:4,radiusY:4,force:1});await input.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point(0)]});for(let i=1;i<=5;i++)await input.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point(i/5)]});await input.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await input.detach();await page.waitForTimeout(550);}

 evidence.fixtureCollisions={};for(const kind of ['enemy','ally','wall','water','bridge']){await collisionFixture(kind);const before=await snap();await page.screenshot({path:dir+'/supplemental-charge-'+kind+'-before.png'});await dragCharge(kind==='bridge'?0:-140,kind==='bridge'?100:0);const after=await snap();evidence.fixtureCollisions[kind]={before,after};await page.screenshot({path:dir+'/supplemental-charge-'+kind+'-after.png'});if(kind==='enemy')check(after.units['red-collision-enemy'].hp===200&&after.units['red-collision-enemy'].statuses.some(s=>s.type==='slow')&&Math.hypot(after.hero.x-700,after.hero.y-575)>=32-1e-7,'Mobile drag Charge damages first enemy once and preserves grounded separation');if(kind==='ally')check(after.units['blue-collision-ally'].hp===240&&after.hero.x>=732-1e-7,'Mobile drag Charge stops harmlessly at allied footprint');if(kind==='wall')check(after.hero.x>=740-1e-7&&after.units.guardian.y===575,'Mobile drag Charge cannot cross an intact Wall or slide around it');if(kind==='water')check(after.hero.x>=1060-1e-7&&after.hero.y===500,'Mobile drag Charge cannot tunnel through river bank');if(kind==='bridge')check(after.hero.y<=595+1e-7&&after.hero.x===960,'Mobile drag Charge stops at radius-safe bridge boundary');}
 // Three independent real touch pointers, cancellation and shared cast lock.
 await collisionFixture('enemy');
 const controls=await page.evaluate(()=>{const h=window.kingdomGame.scene.getScene('HUD'),r=window.kingdomGame.canvas.getBoundingClientRect();return {w:{x:h.abilities[1].x,y:h.abilities[1].y},e:{x:h.abilities[2].x,y:h.abilities[2].y},rect:{x:r.x,y:r.y,width:r.width,height:r.height}};});const cdp=await page.context().newCDPSession(page),touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(p=>({id:p.id,x:controls.rect.x+p.x*controls.rect.width/960,y:controls.rect.y+p.y*controls.rect.height/540,radiusX:4,radiusY:4,force:1}))});
 await touch('touchStart',[{id:1,x:104,y:447},{id:2,...controls.w},{id:3,...controls.e}]);await touch('touchMove',[{id:1,x:128,y:447},{id:2,...controls.w},{id:3,...controls.e}]);check(await page.evaluate(()=>{const h=window.kingdomGame.scene.getScene('HUD');return h.stickPointer!==null&&h.abilities[1].pressed&&h.abilities[2].pressed;}),'844x390 three-pointer joystick plus two skills retain independent ownership');await touch('touchCancel',[]);await page.waitForTimeout(150);check(await page.evaluate(()=>{const h=window.kingdomGame.scene.getScene('HUD');return h.stickPointer===null&&h.abilities.every(a=>!a.pressed)&&window.kingdomGame.scene.getScene('Battle').simulation.state.skills.ready.charge===0;}),'Touch cancellation clears movement/aim without spending Charge cooldown');
 await collisionFixture('enemy');const cancellationStart=await snap();const cancelAim=await page.evaluate(()=>{const a=window.kingdomGame.scene.getScene('HUD').abilities.find(a=>a.id==='charge');return {x:650-a.x-7,y:345-a.y-11};});await dragCharge(cancelAim.x,cancelAim.y);evidence.fixtureCancelRing=await snap();check(evidence.fixtureCancelRing.skills.ready.charge===0&&evidence.fixtureCancelRing.events.filter(e=>e.type==='cast-accepted').length===cancellationStart.events.filter(e=>e.type==='cast-accepted').length,'Mobile red-ring drag release cancels before acceptance without cooldown');
 await collisionFixture('enemy');await page.evaluate(()=>{const s=window.kingdomGame.scene.getScene('Battle').simulation,e=s.state.units['red-collision-enemy'];s.hero.hp=1;e.x=s.hero.x+40;e.damage=18;e.readyTick=0;const hit=s.hit;s.hit=function(...args){const hp=this.hero.hp,result=hit.apply(this,args);if(hp>0&&this.hero.hp===0)window.fixtureSkillDeath=this.clock.tick;return result;};});await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').hero.hp===0);evidence.fixtureDeath=await snap();check(evidence.fixtureDeath.hero.respawnTick-await page.evaluate(()=>window.fixtureSkillDeath)===606,'Supplemental LV20 actual combat death records20.2-second authoritative respawn');await click(770,46);const paused=await snap();await page.waitForTimeout(250);check((await snap()).tick===paused.tick,'Pause freezes skill cooldowns and pending respawn');await click(480,300);await page.waitForFunction(()=>window.kingdomGame.scene.getScene('Battle').hero.hp>0,null,{timeout:30000});evidence.fixtureRespawn=await snap();check(evidence.fixtureRespawn.hero.hp===2574&&evidence.fixtureRespawn.progression.fortitude===2&&evidence.fixtureRespawn.skills.zones.length===0,'Respawn preserves learned stats/points and clears temporary statuses');await win();await restart();const reset=await snap();check(reset.progression.level===1&&reset.progression.fortitude===0&&reset.skills.zones.length===0&&JSON.stringify(reset.listeners)===JSON.stringify(initial.listeners),'Repeated UI Restart resets high-level fixture state with stable listeners');
 check(errors.length===0,'No browser, console or missing-asset errors');
}catch(e){errors.push(e.stack||String(e));try{evidence.failure=await snap();await page.screenshot({path:`${dir}/failure.png`});}catch{}}
finally{await browser.close();await writeFile(`${root}/skills-${variant}.json`,JSON.stringify({url,checks,errors,evidence,limitations:'R/high-level scenarios explicitly supplemental; normal Q/W/E progression uses unchanged waves and actual controls.'},null,2));}
console.log(JSON.stringify({url,checks:checks.length,errors},null,2));if(errors.length)process.exitCode=1;
